import { AdminTable, Field } from "@/components/admin-ui";
import { createServiceRoleClient } from "@/supabase/server";
import { createBankAction, updateBankAction, deactivateBankAction } from "@/app/admin/financing-actions";

export default async function BanksPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const p=await searchParams;const r=await createServiceRoleClient().from("banks").select("id,name,name_ru,code,logo_url,website_url,phone,description,is_active,integration_status").order("display_order").order("name");
 return <div><h1 className="text-3xl font-black">Banklar</h1>{p.error&&<div className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{p.error}</div>}{p.success&&<div className="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">Amal muvaffaqiyatli bajarildi.</div>}
 <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]"><AdminTable><thead className="border-b bg-slate-50"><tr><th className="p-3">Bank</th><th className="p-3">Kod</th><th className="p-3">Holat</th><th className="p-3">Integratsiya</th><th className="p-3">Amallar</th></tr></thead><tbody>{(r.data??[]).map(b=><tr key={b.id} className="border-b align-top"><td className="p-3 font-semibold">{b.name}</td><td className="p-3">{b.code}</td><td className="p-3">{b.is_active?"Faol":"Nofaol"}</td><td className="p-3">{b.integration_status}</td><td className="p-3"><details><summary className="cursor-pointer rounded-lg border px-3 py-2 text-sm font-bold">Tahrirlash</summary><form action={updateBankAction} className="mt-3 min-w-[280px] space-y-3 rounded-xl border bg-slate-50 p-3"><input type="hidden" name="id" value={b.id}/><Field name="name" label="Nomi UZ" defaultValue={b.name} required/><Field name="nameRu" label="Nomi RU" defaultValue={b.name_ru??""}/><Field name="code" label="Kod" defaultValue={b.code} required/><Field name="logoUrl" label="Logo URL" defaultValue={b.logo_url??""}/><Field name="websiteUrl" label="Sayt" defaultValue={b.website_url??""}/><Field name="phone" label="Telefon" defaultValue={b.phone??""}/><label className="block text-sm font-semibold">Izoh<textarea name="description" defaultValue={b.description??""} className="mt-1 w-full rounded border p-3"/></label><label className="block text-sm font-semibold">Integratsiya<select name="integrationStatus" defaultValue={b.integration_status??"information_only"} className="mt-1 w-full rounded border p-2"><option value="information_only">Ma&apos;lumot uchun</option><option value="connected">Ulangan</option><option value="disabled">Faol emas</option></select></label><label className="flex gap-2"><input type="checkbox" name="isActive" defaultChecked={b.is_active}/>Faol</label><button className="w-full rounded-full bg-slate-950 py-2 font-bold text-white">Saqlash</button></form>{b.is_active&&<form action={deactivateBankAction} className="mt-2"><input type="hidden" name="id" value={b.id}/><button className="w-full rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Nofaol qilish</button></form>}</details></td></tr>)}</tbody></AdminTable>
 <form action={createBankAction} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Yangi bank</h2><Field name="name" label="Nomi UZ" required/><Field name="nameRu" label="Nomi RU"/><Field name="code" label="Kod" required/><Field name="logoUrl" label="Logo URL"/><Field name="websiteUrl" label="Sayt"/><Field name="phone" label="Telefon"/><label className="block text-sm font-semibold">Izoh<textarea name="description" className="mt-1 w-full rounded border p-3"/></label><label className="block text-sm font-semibold">Integratsiya<select name="integrationStatus" className="mt-1 w-full rounded border p-2"><option value="information_only">Ma&apos;lumot uchun</option><option value="connected">Ulangan</option><option value="disabled">Faol emas</option></select></label><label className="flex gap-2"><input type="checkbox" name="isActive" defaultChecked/>Faol</label><button className="w-full rounded-full bg-slate-950 py-3 font-bold text-white">Saqlash</button></form></div></div>}
