import Link from "next/link";
import { Header, Footer } from "@/components/site-chrome";
import { AccountLoginGate } from "@/components/account-login-gate";
import { formatPrice } from "@/lib/formatters";
import { getCurrentCustomer } from "@/lib/customer-session";
import { OrderService } from "@/services/order-service";
const STATUS_LABELS:Record<string,string>={pending:"Kutilmoqda",confirmed:"Tasdiqlandi",processing:"Jarayonda",completed:"Bajarildi",cancelled:"Bekor qilindi"};
function carFrom(order:{cars?:unknown}){const r=order.cars;const c=Array.isArray(r)?r[0]:r;return c as {name:string;slug:string}|null;}
export default async function MyOrdersPage(){const customer=await getCurrentCustomer();if(!customer)return <><Header/><main className="mx-auto max-w-7xl px-5 py-12"><h1 className="text-3xl font-black">Mening buyurtmalarim</h1><div className="mt-8"><AccountLoginGate/></div></main><Footer/></>;const result=await new OrderService().findForCustomer(customer.id);const orders=result.data??[];return <><Header/><main className="mx-auto max-w-7xl px-5 py-12"><h1 className="text-3xl font-black">Mening buyurtmalarim</h1>{orders.length===0?<p className="mt-6 text-slate-600">Hozircha buyurtmalar yo’q.</p>:<div className="mt-8 space-y-4">{orders.map(order=>{const car=carFrom(order);return <Link key={order.id} href={`/account/orders/${order.id}`} className="flex flex-col gap-2 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-xs font-semibold text-slate-500">{order.order_number}</p><p className="mt-1 text-lg font-bold">{car?.name??"Avtomobil"}</p><p className="mt-1 text-sm text-slate-500">{new Date(order.created_at).toLocaleDateString("uz-UZ")}</p></div><div className="text-right"><p className="font-bold">{formatPrice(order.total_amount,order.currency)}</p><span className="mt-1 inline-block rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{STATUS_LABELS[order.status]??order.status}</span></div></Link>})}</div>}</main><Footer/></>}
