"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireAdminUser } from "@/lib/admin-auth";
import { AdminCatalogService } from "@/services/admin-catalog-service";
const text=(formData:FormData,key:string)=>{const value=formData.get(key);return typeof value==="string"&&value.trim()?value.trim():null;}; const number=(formData:FormData,key:string)=>{const value=text(formData,key);return value===null?null:Number(value);}; const checked=(formData:FormData,key:string)=>formData.get(key)==="on";
function slugify(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[‘’'`]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);}
function friendlyCarError(error:unknown){const e=error as {message?:string;code?:string};if(e?.code==="23505")return "Bu avtomobil slug'i allaqachon mavjud.";if(e?.code==="23503")return "Tanlangan brend yoki model bazada mavjud emas.";return e?.message||"Avtomobilni saqlashda noma'lum xatolik yuz berdi.";}
export async function createBrandAction(formData:FormData){const user=await requireAdminUser();const service=new AdminCatalogService();await service.createBrand({name:text(formData,"name"),slug:text(formData,"slug"),description:text(formData,"description"),logoUrl:text(formData,"logoUrl"),isActive:checked(formData,"isActive")},user.id);revalidatePath("/admin/brands");revalidatePath("/");revalidatePath("/cars");}
export async function createModelAction(formData:FormData){const user=await requireAdminUser();const service=new AdminCatalogService();await service.createModel({brandId:text(formData,"brandId"),name:text(formData,"name"),slug:text(formData,"slug"),description:text(formData,"description"),isActive:checked(formData,"isActive")},user.id);revalidatePath("/admin/models");}
export async function createCarAction(formData:FormData){try{const user=await requireAdminUser();const service=new AdminCatalogService();const name=text(formData,"name");if(!name)throw new Error("Avtomobil nomini kiriting.");const generatedSlug=slugify(name);if(!generatedSlug)throw new Error("Avtomobil nomidan yaroqli slug yaratib bo'lmadi.");const result=await service.createCar({brandId:text(formData,"brandId"),modelId:text(formData,"modelId"),name,slug:generatedSlug,shortDescription:text(formData,"shortDescription"),description:text(formData,"description"),price:number(formData,"price"),currency:text(formData,"currency")??"UZS",oldPrice:number(formData,"oldPrice"),year:number(formData,"year"),bodyType:text(formData,"bodyType"),fuelType:text(formData,"fuelType"),transmission:text(formData,"transmission"),driveType:text(formData,"driveType"),engineVolume:number(formData,"engineVolume"),enginePower:number(formData,"enginePower"),rangeKm:number(formData,"rangeKm"),seats:number(formData,"seats"),color:text(formData,"color"),stockStatus:text(formData,"stockStatus")??"coming_soon",isFeatured:checked(formData,"isFeatured"),isActive:checked(formData,"isActive")},user.id);if(result.error)throw result.error;revalidatePath("/admin/cars");revalidatePath("/");revalidatePath("/cars");}catch(error){redirect(`/admin/cars?error=${encodeURIComponent(friendlyCarError(error))}`);}}
export async function deactivateAction(formData:FormData){const user=await requireAdminUser();const kind=text(formData,"kind");const id=text(formData,"id");if((kind!=="brands"&&kind!=="car_models"&&kind!=="cars")||!id)throw new Error("Noto‘g‘ri so‘rov");await new AdminCatalogService().deactivate(kind,id,user.id);revalidatePath("/admin");revalidatePath("/");revalidatePath("/cars");}
