"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminUser } from "@/lib/admin-auth";
import { createServiceRoleClient } from "@/supabase/server";
const value=(data:FormData,key:string)=>{const v=data.get(key);return typeof v==="string"&&v.trim()?v.trim():null;};
export async function createDealerAction(data:FormData){const user=await requireAdminUser();const name=value(data,"name");if(!name)redirect("/admin/dealers?error=Dealer+nomini+kiriting");const c=createServiceRoleClient();const result=await c.from("dealers").insert({name,region:value(data,"region"),phone:value(data,"phone"),description:value(data,"description"),is_active:data.get("isActive")==="on"}).select("id").single();if(result.error)redirect(`/admin/dealers?error=${encodeURIComponent(result.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"dealer.created",entity_type:"dealer",entity_id:result.data.id,metadata:{}});revalidatePath("/admin/dealers");revalidatePath("/admin/cars");redirect("/admin/dealers?success=created");}
export async function updateDealerAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");const name=value(data,"name");if(!id||!name)redirect("/admin/dealers?error=Diler+ID+va+nomi+majburiy");const c=createServiceRoleClient();const result=await c.from("dealers").update({name,region:value(data,"region"),phone:value(data,"phone"),description:value(data,"description"),is_active:data.get("isActive")==="on"}).eq("id",id);if(result.error)redirect(`/admin/dealers?error=${encodeURIComponent(result.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"dealer.updated",entity_type:"dealer",entity_id:id,metadata:{}});revalidatePath("/admin/dealers");revalidatePath("/admin/cars");redirect("/admin/dealers?success=updated");}
export async function deactivateDealerAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");if(!id)throw new Error("So‘rov yaroqsiz");const c=createServiceRoleClient();await c.from("dealers").update({is_active:false}).eq("id",id);await c.from("audit_logs").insert({actor_id:user.id,action:"dealer.deactivated",entity_type:"dealer",entity_id:id,metadata:{}});revalidatePath("/admin/dealers");revalidatePath("/admin/cars");}
