"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminUser } from "@/lib/admin-auth";
import { createServiceRoleClient } from "@/supabase/server";

type RuleInput={down_payment_percent:number;term_months:number;annual_interest_rate:number;is_available:boolean;display_order:number};
const value=(d:FormData,k:string)=>{const v=d.get(k);return typeof v==="string"&&v.trim()?v.trim():null};
const num=(d:FormData,k:string)=>{const v=value(d,k);return v===null?null:Number(v.replace(",","."))};
const selected=(d:FormData,k:string)=>d.getAll(k).filter((v):v is string=>typeof v==="string"&&v.length>0);
const parseRules=(d:FormData):RuleInput[]=>{const raw=value(d,"rulesJson");if(!raw)return[];try{const parsed:unknown=JSON.parse(raw);if(!Array.isArray(parsed))return[];return parsed.map((item:unknown,i)=>{if(!item||typeof item!=="object")return null;const r=item as Record<string,unknown>;const down=Number(r.down_payment_percent),term=Number(r.term_months),rate=Number(r.annual_interest_rate);if(!Number.isFinite(down)||!Number.isFinite(term)||term<=0||!Number.isFinite(rate)||down<0||down>100)return null;return{down_payment_percent:down,term_months:term,annual_interest_rate:rate,is_available:r.is_available!==false,display_order:i};}).filter((r):r is RuleInput=>r!==null);}catch{return[]}};
async function replaceRules(c:ReturnType<typeof createServiceRoleClient>,programId:string,d:FormData){const rules=parseRules(d);await c.from("financing_program_rules").delete().eq("financing_program_id",programId);if(rules.length){const r=await c.from("financing_program_rules").insert(rules.map(rule=>({...rule,financing_program_id:programId})));if(r.error)throw new Error(r.error.message);}}
export async function createBankAction(d:FormData){const user=await requireAdminUser();const name=value(d,"name"),code=value(d,"code");if(!name||!code)redirect("/admin/banks?error=Bank+nomi+va+kodi+majburiy");const c=createServiceRoleClient();const r=await c.from("banks").insert({name,name_ru:value(d,"nameRu"),code,logo_url:value(d,"logoUrl"),website_url:value(d,"websiteUrl"),phone:value(d,"phone"),description:value(d,"description"),is_active:d.get("isActive")==="on",integration_status:value(d,"integrationStatus")??"information_only"}).select("id").single();if(r.error)redirect(`/admin/banks?error=${encodeURIComponent(r.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"bank.created",entity_type:"bank",entity_id:r.data.id,metadata:{}});revalidatePath("/admin/banks");revalidatePath("/admin/financing-programs");redirect("/admin/banks?success=created")}
export async function updateBankAction(d:FormData){const user=await requireAdminUser();const id=value(d,"id"),name=value(d,"name"),code=value(d,"code");if(!id||!name||!code)redirect("/admin/banks?error=Bank+ID%2C+nomi+va+kodi+majburiy");const c=createServiceRoleClient();const r=await c.from("banks").update({name,name_ru:value(d,"nameRu"),code,logo_url:value(d,"logoUrl"),website_url:value(d,"websiteUrl"),phone:value(d,"phone"),description:value(d,"description"),is_active:d.get("isActive")==="on",integration_status:value(d,"integrationStatus")??"information_only"}).eq("id",id).select("id").single();if(r.error)redirect(`/admin/banks?error=${encodeURIComponent(r.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"bank.updated",entity_type:"bank",entity_id:id,metadata:{}});revalidatePath("/admin/banks");revalidatePath("/admin/financing-programs");revalidatePath("/");redirect("/admin/banks?success=updated")}
export async function deactivateBankAction(d:FormData){const user=await requireAdminUser();const id=value(d,"id");if(!id)redirect("/admin/banks?error=Bank+ID+topilmadi");const c=createServiceRoleClient();const r=await c.from("banks").update({is_active:false}).eq("id",id);if(r.error)redirect(`/admin/banks?error=${encodeURIComponent(r.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"bank.deactivated",entity_type:"bank",entity_id:id,metadata:{}});revalidatePath("/admin/banks");revalidatePath("/admin/financing-programs");revalidatePath("/");redirect("/admin/banks?success=deactivated")}
async function programPayload(d:FormData){const minTerm=num(d,"minTermMonths"),maxTerm=num(d,"maxTermMonths");return{bank_id:value(d,"bankId"),name:value(d,"name"),name_uz:value(d,"nameUz")??value(d,"name"),name_ru:value(d,"nameRu"),type:value(d,"financingType"),interest_rate:num(d,"annualInterestRate")??0,down_payment_percent:num(d,"minDownPaymentPercent")??0,min_term_months:minTerm,term_months:maxTerm??minTerm??12,commission_percent:num(d,"commissionPercent")??0,min_car_price:num(d,"minCarPrice"),max_car_price:num(d,"maxCarPrice"),min_amount:num(d,"minAmount"),max_amount:num(d,"maxAmount"),max_financing_percent:num(d,"maxFinancingPercent"),insurance_type:value(d,"insuranceType"),insurance_amount:num(d,"insuranceAmount"),insurance_percent:num(d,"insurancePercent"),benefits_uz:value(d,"benefitsUz"),benefits_ru:value(d,"benefitsRu"),description:value(d,"description"),eligibility_notes:value(d,"eligibilityNotes"),currency:value(d,"currency")??"UZS",is_active:d.get("isActive")==="on",sort_order:num(d,"displayOrder")??0,source_url:value(d,"sourceUrl"),source_label:value(d,"sourceLabel"),last_verified_at:new Date().toISOString()};}
function validateTerms(d:FormData){const min=num(d,"minTermMonths"),max=num(d,"maxTermMonths");return min!==null&&max!==null&&(min<1||max<min)?"Muddat oralig‘i noto‘g‘ri":null}
export async function createFinancingProgramAction(d:FormData){const user=await requireAdminUser();const type=value(d,"financingType"),name=value(d,"name"),bankId=value(d,"bankId");if(!name||!["credit","installment"].includes(type??""))redirect("/admin/financing-programs?error=Nom+va+turi+majburiy");if(type==="credit"&&!bankId)redirect("/admin/financing-programs?error=Bank+kredit+uchun+majburiy");const termError=validateTerms(d);if(termError)redirect(`/admin/financing-programs?error=${encodeURIComponent(termError)}`);const c=createServiceRoleClient();try{const r=await c.from("financing_programs").insert(await programPayload(d)).select("id").single();if(r.error)throw new Error(r.error.message);await replaceRules(c,r.data.id,d);const dealerIds=selected(d,"dealerIds"),carIds=selected(d,"carIds");if(dealerIds.length)await c.from("financing_program_dealers").insert(dealerIds.map(dealer_id=>({dealer_id,financing_program_id:r.data.id})));if(carIds.length)await c.from("financing_program_cars").insert(carIds.map(car_id=>({car_id,financing_program_id:r.data.id})));await c.from("audit_logs").insert({actor_id:user.id,action:"financing_program.created",entity_type:"financing_program",entity_id:r.data.id,metadata:{type,bankId,ruleCount:parseRules(d).length}});}catch(error){redirect(`/admin/financing-programs?error=${encodeURIComponent(error instanceof Error?error.message:"Dastur saqlanmadi")}`)}revalidatePath("/admin/financing-programs");revalidatePath("/");revalidatePath("/cars");redirect("/admin/financing-programs?success=created")}
export async function updateFinancingProgramAction(d:FormData){const user=await requireAdminUser();const id=value(d,"id"),type=value(d,"financingType"),name=value(d,"name"),bankId=value(d,"bankId");if(!id||!name||!["credit","installment"].includes(type??""))redirect("/admin/financing-programs?error=Ma%27lumotlar+to%27liq+emas");if(type==="credit"&&!bankId)redirect("/admin/financing-programs?error=Bank+kredit+uchun+majburiy");const termError=validateTerms(d);if(termError)redirect(`/admin/financing-programs?error=${encodeURIComponent(termError)}`);const c=createServiceRoleClient();try{const r=await c.from("financing_programs").update(await programPayload(d)).eq("id",id).select("id").single();if(r.error)throw new Error(r.error.message);await replaceRules(c,id,d);await c.from("financing_program_dealers").delete().eq("financing_program_id",id);await c.from("financing_program_cars").delete().eq("financing_program_id",id);const dealerIds=selected(d,"dealerIds"),carIds=selected(d,"carIds");if(dealerIds.length)await c.from("financing_program_dealers").insert(dealerIds.map(dealer_id=>({dealer_id,financing_program_id:id})));if(carIds.length)await c.from("financing_program_cars").insert(carIds.map(car_id=>({car_id,financing_program_id:id})));await c.from("audit_logs").insert({actor_id:user.id,action:"financing_program.updated",entity_type:"financing_program",entity_id:id,metadata:{minTerm:num(d,"minTermMonths"),maxTerm:num(d,"maxTermMonths"),ruleCount:parseRules(d).length}});}catch(error){redirect(`/admin/financing-programs?error=${encodeURIComponent(error instanceof Error?error.message:"Dastur saqlanmadi")}`)}revalidatePath("/admin/financing-programs");revalidatePath("/");revalidatePath("/cars");redirect("/admin/financing-programs?success=updated")}
export async function deactivateFinancingProgramAction(d:FormData){const user=await requireAdminUser();const id=value(d,"id");if(!id)redirect("/admin/financing-programs?error=ID+topilmadi");const c=createServiceRoleClient();const r=await c.from("financing_programs").update({is_active:false}).eq("id",id);if(r.error)redirect(`/admin/financing-programs?error=${encodeURIComponent(r.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"financing_program.deactivated",entity_type:"financing_program",entity_id:id,metadata:{}});revalidatePath("/admin/financing-programs");revalidatePath("/");revalidatePath("/cars");redirect("/admin/financing-programs?success=deactivated")}