"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminUser } from "@/lib/admin-auth";
import { createServiceRoleClient } from "@/supabase/server";
const value=(d:FormData,k:string)=>{const v=d.get(k);return typeof v==="string"&&v.trim()?v.trim():null;};
const num=(d:FormData,k:string)=>{const v=value(d,k);return v===null?null:Number(v);};
const selected=(d:FormData,k:string)=>d.getAll(k).filter((v):v is string=>typeof v==="string"&&v.length>0);
export async function createBankAction(d:FormData){const user=await requireAdminUser();const name=value(d,"name");const code=value(d,"code");if(!name||!code)redirect("/admin/banks?error=Bank+nomi+va+kodi+majburiy");const c=createServiceRoleClient();const r=await c.from("banks").insert({name,name_ru:value(d,"nameRu"),code,logo_url:value(d,"logoUrl"),website_url:value(d,"websiteUrl"),phone:value(d,"phone"),description:value(d,"description"),is_active:d.get("isActive")==="on",integration_status:value(d,"integrationStatus")??"information_only"}).select("id").single();if(r.error)redirect(`/admin/banks?error=${encodeURIComponent(r.error.message)}`);await c.from("audit_logs").insert({actor_id:user.id,action:"bank.created",entity_type:"bank",entity_id:r.data.id,metadata:{}});revalidatePath("/admin/banks");revalidatePath("/admin/financing-programs");redirect("/admin/banks?success=created");}
export async function createFinancingProgramAction(d:FormData){const user=await requireAdminUser();const bankId=value(d,"bankId");const name=value(d,"name");const type=value(d,"financingType");if(!bankId||!name||!["credit","installment","promotional"].includes(type??""))redirect("/admin/financing-programs?error=Bank%2C+nom+va+turi+majburiy");const c=createServiceRoleClient();const r=await c.from("financing_programs").insert({bank_id:bankId,name,name_ru:value(d,"nameRu"),financing_type:type,annual_interest_rate:num(d,"annualInterestRate"),min_down_payment_percent:num(d,"minDownPaymentPercent"),max_financing_percent:num(d,"maxFinancingPercent"),min_term_months:num(d,"minTermMonths"),max_term_months:num(d,"maxTermMonths"),min_amount:num(d,"minAmount"),max_amount:num(d,"maxAmount"),commission_percent:num(d,"commissionPercent"),description:value(d,"description"),is_active:d.get("isActive")==="on",display_order:num(d,"displayOrder")??0}).select("id").single();if(r.error)redirect(`/admin/financing-programs?error=${encodeURIComponent(r.error.message)}`);const dealerIds=selected(d,"dealerIds");if(dealerIds.length){const links=await c.from("dealer_financing_programs").insert(dealerIds.map(dealer_id=>({dealer_id,financing_program_id:r.data.id})));if(links.error)redirect(`/admin/financing-programs?error=${encodeURIComponent(links.error.message)}`);}const carIds=selected(d,"carIds");if(carIds.length){const links=await c.from("financing_program_cars").insert(carIds.map(car_id=>({car_id,financing_program_id:r.data.id})));if(links.error)redirect(`/admin/financing-programs?error=${encodeURIComponent(links.error.message)}`);}await c.from("audit_logs").insert({actor_id:user.id,action:"financing_program.created",entity_type:"financing_program",entity_id:r.data.id,metadata:{}});revalidatePath("/admin/financing-programs");revalidatePath("/");revalidatePath("/cars");redirect("/admin/financing-programs?success=created");}
