"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation"; import { requireAdminUser } from "@/lib/admin-auth"; import { AdminRefinementService } from "@/services/admin-refinement-service";
const value=(data:FormData,key:string)=>{const x=data.get(key);return typeof x==="string"&&x.trim()?x.trim():null;};
const numeric=(data:FormData,key:string)=>{const x=value(data,key);return x===null?null:Number(x.replace(",","."));};
const flag=(data:FormData,key:string)=>data.get(key)==="on";
export async function updateBrandAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");if(!id)throw new Error("So‘rov yaroqsiz");await new AdminRefinementService().updateBrand(id,{name:value(data,"name"),slug:value(data,"slug"),description:value(data,"description"),logoUrl:value(data,"logoUrl"),isActive:flag(data,"isActive")},user.id);revalidatePath("/admin/brands");redirect("/admin/brands?success=updated");}
export async function updateModelAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");if(!id)throw new Error("So‘rov yaroqsiz");await new AdminRefinementService().updateModel(id,{brandId:value(data,"brandId"),name:value(data,"name"),slug:value(data,"slug"),description:value(data,"description"),isActive:flag(data,"isActive")},user.id);revalidatePath("/admin/models");redirect("/admin/models?success=updated");}
export async function updateCarAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");if(!id)throw new Error("So‘rov yaroqsiz");await new AdminRefinementService().updateCar(id,{brandId:value(data,"brandId"),modelId:value(data,"modelId"),dealerId:value(data,"dealerId"),name:value(data,"name"),slug:value(data,"slug"),shortDescription:value(data,"shortDescription"),description:value(data,"description"),price:numeric(data,"price"),currency:value(data,"currency")??"UZS",oldPrice:numeric(data,"oldPrice"),year:numeric(data,"year"),bodyType:value(data,"bodyType"),fuelType:value(data,"fuelType"),transmission:value(data,"transmission"),driveType:value(data,"driveType"),engineVolume:numeric(data,"engineVolume"),enginePower:numeric(data,"enginePower"),rangeKm:numeric(data,"rangeKm"),seats:numeric(data,"seats"),color:value(data,"color"),stockStatus:value(data,"stockStatus")??"coming_soon",isFeatured:flag(data,"isFeatured"),isPremium:flag(data,"isPremium"),isCommercial:flag(data,"isCommercial"),isActive:flag(data,"isActive")},user.id);revalidatePath("/admin/cars");revalidatePath("/cars");redirect("/admin/cars?success=updated");}
export async function reorderImageAction(data:FormData){const user=await requireAdminUser();const carId=value(data,"carId");const imageId=value(data,"imageId");const direction=value(data,"direction")==="up"?-1:1;if(!carId||!imageId)throw new Error("So‘rov yaroqsiz");await new AdminRefinementService().reorderImage(carId,imageId,direction,user.id);revalidatePath("/admin/cars/"+carId+"/images");revalidatePath("/cars");}
export async function deleteRefinedImageAction(data:FormData){const user=await requireAdminUser();const carId=value(data,"carId");const imageId=value(data,"imageId");if(!carId||!imageId)throw new Error("So‘rov yaroqsiz");await new AdminRefinementService().deleteImage(carId,imageId,user.id);revalidatePath("/admin/cars/"+carId+"/images");revalidatePath("/cars");}
