"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminUser } from "@/lib/admin-auth";
import { createServiceRoleClient } from "@/supabase/server";
const value=(d:FormData,k:string)=>{const v=d.get(k);return typeof v==="string"&&v.trim()?v.trim():null;};
async function audit(entityType:string,entityId:string,action:string,userId:string){await createServiceRoleClient().from("audit_logs").insert({actor_id:userId,action,entity_type:entityType,entity_id:entityId,metadata:{source:"admin_translations"}});}
export async function saveBankTranslationAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");const nameRu=value(data,"nameRu");if(!id||!nameRu)redirect("/admin/translations?error=Bank+ruscha+nomini+kiriting");const c=createServiceRoleClient();const r=await c.from("banks").update({name_ru:nameRu}).eq("id",id);if(r.error)redirect(`/admin/translations?error=${encodeURIComponent(r.error.message)}`);await audit("bank",id,"bank.translation.updated",user.id);revalidatePath("/admin/translations");revalidatePath("/cars", "layout");redirect("/admin/translations?success=bank");}
export async function saveDealerTranslationAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");const nameRu=value(data,"nameRu");if(!id||!nameRu)redirect("/admin/translations?error=Diler+ruscha+nomini+kiriting");const c=createServiceRoleClient();const r=await c.from("dealers").update({name_ru:nameRu,region_ru:value(data,"regionRu"),description_ru:value(data,"descriptionRu")}).eq("id",id);if(r.error)redirect(`/admin/translations?error=${encodeURIComponent(r.error.message)}`);await audit("dealer",id,"dealer.translation.updated",user.id);revalidatePath("/admin/translations");revalidatePath("/cars", "layout");redirect("/admin/translations?success=dealer");}
export async function saveProgramTranslationAction(data:FormData){const user=await requireAdminUser();const id=value(data,"id");const nameRu=value(data,"nameRu");if(!id||!nameRu)redirect("/admin/translations?error=Kredit+dasturining+ruscha+nomini+kiriting");const c=createServiceRoleClient();const r=await c.from("financing_programs").update({name_ru:nameRu,description_ru:value(data,"descriptionRu"),eligibility_notes_ru:value(data,"eligibilityNotesRu"),insurance_type_ru:value(data,"insuranceTypeRu")}).eq("id",id);if(r.error)redirect(`/admin/translations?error=${encodeURIComponent(r.error.message)}`);await audit("financing_program",id,"financing_program.translation.updated",user.id);revalidatePath("/admin/translations");revalidatePath("/cars", "layout");redirect("/admin/translations?success=program");}
