import "server-only";
import { createServiceRoleClient } from "@/supabase/server";
export class AdminRefinementRepository {
 private client(){return createServiceRoleClient();}
 brand(id:string){return this.client().from("brands").select("*").eq("id",id).single();}
 model(id:string){return this.client().from("car_models").select("*").eq("id",id).single();}
 car(id:string){return this.client().from("cars").select("*").eq("id",id).single();}
 async modelMatchesBrand(modelId:string,brandId:string){const r=await this.client().from("car_models").select("id").eq("id",modelId).eq("brand_id",brandId).maybeSingle();return Boolean(r.data);}
 updateBrand(id:string,input:Record<string,unknown>){return this.client().from("brands").update({name:input.name,slug:input.slug,description:input.description,logo_url:input.logoUrl,is_active:input.isActive}).eq("id",id).select().single();}
 updateModel(id:string,input:Record<string,unknown>){return this.client().from("car_models").update({brand_id:input.brandId,name:input.name,slug:input.slug,description:input.description,is_active:input.isActive}).eq("id",id).select().single();}
 updateCar(id:string,input:Record<string,unknown>){return this.client().from("cars").update({brand_id:input.brandId,model_id:input.modelId,dealer_id:input.dealerId??null,name:input.name,slug:input.slug,short_description:input.shortDescription,description:input.description,price:input.price,currency:input.currency,old_price:input.oldPrice,year:input.year,body_type:input.bodyType,fuel_type:input.fuelType,transmission:input.transmission,drive_type:input.driveType,engine_volume:input.engineVolume,engine_type:input.engineType,engine_power:input.enginePower,range_km:input.rangeKm,battery_capacity_kwh:input.batteryCapacityKwh,acceleration_0_100_sec:input.acceleration0100Sec,charging_time_minutes:input.chargingTimeMinutes,seats:input.seats,color:input.color,stock_status:input.stockStatus,is_featured:input.isFeatured,is_active:input.isActive}).eq("id",id).select().single();}
 async reorder(carId:string,imageId:string,direction:-1|1){const images=await this.client().from("car_images").select("id,sort_order").eq("car_id",carId).order("sort_order");const rows=images.data??[];const index=rows.findIndex(x=>x.id===imageId);const target=index+direction;if(index<0||target<0||target>=rows.length)return;const current=rows[index];const neighbor=rows[target];await this.client().from("car_images").update({sort_order:neighbor.sort_order}).eq("id",current.id);await this.client().from("car_images").update({sort_order:current.sort_order}).eq("id",neighbor.id);}
 async deleteImage(carId:string,imageId:string){const client=this.client();const image=await client.from("car_images").select("storage_path,is_primary").eq("id",imageId).eq("car_id",carId).single();if(!image.data)return;await client.storage.from("car-images").remove([image.data.storage_path]);await client.from("car_images").delete().eq("id",imageId).eq("car_id",carId);if(image.data.is_primary){const next=await client.from("car_images").select("id").eq("car_id",carId).order("sort_order").limit(1).maybeSingle();if(next.data)await client.from("car_images").update({is_primary:true}).eq("id",next.data.id);}}
}
