import "server-only";
import { createServiceRoleClient } from "@/supabase/server";

type Relation<T> = T | T[] | null;
const first = <T>(v: Relation<T> | undefined): T | null => Array.isArray(v) ? (v[0] ?? null) : (v ?? null);
type Row = { id:string; status:string; purchase_type:string; total_amount:number; manager_overrides:{finance?:{downPaymentAmount?:number;financedAmount?:number;downPaymentPercent?:number}}|null; cars?:Relation<{dealers?:Relation<{id:string;name:string}>}>; financing_programs?:Relation<{id:string;name:string;type:string;down_payment_percent:number;banks?:Relation<{id:string;name:string}>}> };
export type AnalyticsRow={name:string;count:number;amount:number};
export type SalesAnalytics={salesCount:number;salesAmount:number;financingAmount:number;downPaymentAmount:number;averageSale:number;creditSales:number;installmentSales:number;cashSales:number;creditApplications:number;pipelineCount:number;byBank:AnalyticsRow[];byDealer:AnalyticsRow[];byProgram:AnalyticsRow[];byPurchaseType:AnalyticsRow[];byStatus:{name:string;count:number}[]};
export class AdminSalesAnalyticsRepository{async get():Promise<SalesAnalytics>{const client=createServiceRoleClient();const orders=await client.from("orders").select("id,status,purchase_type,total_amount,manager_overrides,cars(dealers(id,name)),financing_programs(id,name,type,down_payment_percent,banks(id,name))");if(orders.error)throw orders.error;const rows=(orders.data??[]) as unknown as Row[];const completed=rows.filter(r=>r.status==="completed");const apps=await client.from("credit_applications").select("id",{count:"exact",head:true});if(apps.error)throw apps.error;const byBank=new Map<string,AnalyticsRow>(),byDealer=new Map<string,AnalyticsRow>(),byProgram=new Map<string,AnalyticsRow>(),byType=new Map<string,AnalyticsRow>(),statusMap=new Map<string,number>();let financingAmount=0,downPaymentAmount=0;for(const row of completed){const total=Number(row.total_amount)||0;const program=first(row.financing_programs),bank=first(program?.banks),dealer=first(first(row.cars)?.dealers),ov=row.manager_overrides?.finance;const down=ov?.downPaymentAmount??total*(Number(ov?.downPaymentPercent??program?.down_payment_percent??0)/100);const financed=ov?.financedAmount??Math.max(0,total-down);if(row.purchase_type==="credit"||row.purchase_type==="installment"){financingAmount+=financed;downPaymentAmount+=down;}add(byType,labelType(row.purchase_type),1,total);if(bank&&row.purchase_type==="credit")add(byBank,bank.name,1,financed);if(dealer)add(byDealer,dealer.name,1,total);if(program)add(byProgram,program.name,1,financed);}for(const row of rows)statusMap.set(row.status,(statusMap.get(row.status)??0)+1);return{salesCount:completed.length,salesAmount:completed.reduce((s,r)=>s+(Number(r.total_amount)||0),0),financingAmount,downPaymentAmount,averageSale:completed.length?completed.reduce((s,r)=>s+(Number(r.total_amount)||0),0)/completed.length:0,creditSales:completed.filter(r=>r.purchase_type==="credit").length,installmentSales:completed.filter(r=>r.purchase_type==="installment").length,cashSales:completed.filter(r=>r.purchase_type==="cash").length,creditApplications:apps.count??0,pipelineCount:rows.filter(r=>["pending","confirmed","processing"].includes(r.status)).length,byBank:[...byBank.values()].sort((a,b)=>b.amount-a.amount),byDealer:[...byDealer.values()].sort((a,b)=>b.amount-a.amount),byProgram:[...byProgram.values()].sort((a,b)=>b.amount-a.amount),byPurchaseType:[...byType.values()].sort((a,b)=>b.amount-a.amount),byStatus:[...statusMap.entries()].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name:labelStatus(name),count}))};}}
function add(map:Map<string,AnalyticsRow>,name:string,count:number,amount:number){const current=map.get(name)??{name,count:0,amount:0};current.count+=count;current.amount+=amount;map.set(name,current);}
function labelType(type:string){return({cash:"Naqd",credit:"Kredit",installment:"Rassrochka"} as Record<string,string>)[type]??type;}
function labelStatus(status:string){return({pending:"Kutilmoqda",confirmed:"Tasdiqlangan",processing:"Jarayonda",completed:"Bajarilgan",cancelled:"Bekor qilingan"} as Record<string,string>)[status]??status;}
