import "server-only";
import { createServiceRoleClient } from "@/supabase/server";
import type { OrderStatus, PurchaseType } from "@/types/domain";
type SingleOrArray<T> = T | T[] | null;
const firstRelation = <T>(relation: SingleOrArray<T> | undefined): T | null => Array.isArray(relation) ? relation[0] ?? null : relation ?? null;
type Profile = { id?: string; phone: string | null; full_name: string | null };
type Credit = { status: string };
type Car = { id: string; name: string | null; name_uz: string | null; name_ru: string | null };
type Row = { id:string; order_number:string; customer_id:string; car_id:string | null; status:OrderStatus; purchase_type:PurchaseType; total_amount:number; currency:string; created_at:string; updated_at:string; profiles?:SingleOrArray<Profile>; credit_applications?:SingleOrArray<Credit>; cars?:SingleOrArray<Car> };
type HistoryRow = { id:string; old_status:OrderStatus | null; new_status:OrderStatus; changed_at:string; changed_by:string | null; profiles?:SingleOrArray<Profile> };
export type AdminOrderListItem = { id:string; orderNumber:string; customerId:string; carId:string|null; car:Car|null; status:OrderStatus; purchaseType:PurchaseType; totalAmount:number; currency:string; createdAt:string; updatedAt:string; customer:Profile|null; creditApplicationStatus:string|null };
export type OrderStatusHistoryItem = { id:string; oldStatus:OrderStatus|null; newStatus:OrderStatus; changedAt:string; changedBy:string|null; actorName:string|null };
const normalize = (r:Row):AdminOrderListItem => ({ id:r.id, orderNumber:r.order_number, customerId:r.customer_id, carId:r.car_id, car:firstRelation(r.cars), status:r.status, purchaseType:r.purchase_type, totalAmount:r.total_amount, currency:r.currency, createdAt:r.created_at, updatedAt:r.updated_at, customer:firstRelation(r.profiles), creditApplicationStatus:firstRelation(r.credit_applications)?.status ?? null });
export type AdminOrderFilters={status?:OrderStatus;purchaseType?:PurchaseType;carId?:string;dateFrom?:string;dateTo?:string;needsAttention?:boolean};
export class AdminOrderRepository {
  private client(){return createServiceRoleClient();}
  async listOrders(filters:AdminOrderFilters){let q=this.client().from("orders").select("id,order_number,customer_id,car_id,status,purchase_type,total_amount,currency,created_at,updated_at,profiles(id,phone,full_name),credit_applications(status),cars(id,name,name_uz,name_ru)").order("created_at",{ascending:false}); if(filters.status)q=q.eq("status",filters.status);if(filters.purchaseType)q=q.eq("purchase_type",filters.purchaseType);if(filters.carId)q=q.eq("car_id",filters.carId);if(filters.dateFrom)q=q.gte("created_at",filters.dateFrom);if(filters.dateTo)q=q.lte("created_at",filters.dateTo);if(filters.needsAttention)q=q.eq("status","pending");const r=await q;let data=r.data?(r.data as unknown as Row[]).map(normalize):null;if(filters.needsAttention&&data)data=data.filter(o=>o.status==="pending"&&o.creditApplicationStatus==="approved");return {...r,data};}
  async findById(orderId:string){const r=await this.client().from("orders").select("id,order_number,customer_id,car_id,status,purchase_type,total_amount,currency,created_at,updated_at,profiles(id,phone,full_name),credit_applications(status),cars(id,name,name_uz,name_ru)").eq("id",orderId).maybeSingle();return {...r,data:r.data?normalize(r.data as unknown as Row):null};}
  async findCustomerOrders(customerId:string,excludeOrderId?:string){let q=this.client().from("orders").select("id,order_number,customer_id,car_id,status,purchase_type,total_amount,currency,created_at,updated_at,profiles(id,phone,full_name),credit_applications(status),cars(id,name,name_uz,name_ru)").eq("customer_id",customerId).order("created_at",{ascending:false});if(excludeOrderId)q=q.neq("id",excludeOrderId);const r=await q;return {...r,data:r.data?(r.data as unknown as Row[]).map(normalize):null};}
  async findStatusHistory(orderId:string){const r=await this.client().from("order_status_history").select("id,old_status,new_status,changed_at,changed_by,profiles(full_name,phone)").eq("order_id",orderId).order("changed_at",{ascending:true});const data=(r.data??[]) as unknown as HistoryRow[];return {...r,data:data.map(h=>({id:h.id,oldStatus:h.old_status,newStatus:h.new_status,changedAt:h.changed_at,changedBy:h.changed_by,actorName:firstRelation(h.profiles)?.full_name||firstRelation(h.profiles)?.phone||null}))};}
  async updateStatusIfCurrent(orderId:string,current:OrderStatus,next:OrderStatus){return this.client().from("orders").update({status:next}).eq("id",orderId).eq("status",current).select().maybeSingle();}
  async createStatusHistory(input:{orderId:string;oldStatus:OrderStatus;newStatus:OrderStatus;changedBy:string}){return this.client().from("order_status_history").insert({order_id:input.orderId,old_status:input.oldStatus,new_status:input.newStatus,changed_by:input.changedBy}).select().single();}
  async audit(actorId:string,action:string,entityType:string,entityId:string){return this.client().from("audit_logs").insert({actor_id:actorId,action,entity_type:entityType,entity_id:entityId,metadata:{}});}
}
