import "server-only";
import { createPublicServerClient } from "@/supabase/public-server";
import { FinancingRepository } from "@/repositories/financing-repository";
import { PAGE_SIZE, type CatalogQuery } from "@/features/catalog/catalog-query";
import { searchRelevance } from "@/features/catalog/search-utils";

type SingleOrArray<T> = T | T[] | null;
type BrandRelation = { name: string; slug?: string | null; logo_url?: string | null };
type ModelRelation = { name: string; slug?: string | null };
type ColorRelation = { id: string; name_uz: string; name_ru: string; hex_code: string };
type ImageRelation = { public_url: string | null; alt_text: string | null; is_primary: boolean; sort_order: number; color_id?: string | null; car_colors?: SingleOrArray<ColorRelation> };
type CarRelations = { id:string; model_id:string; name:string; slug:string; price:number; currency:string; old_price?:number|null; year:number; stock_status:string; is_featured:boolean; body_type?:string|null; fuel_type?:string|null; transmission?:string|null; drive_type?:string|null; engine_volume?:number|string|null; brands?:SingleOrArray<BrandRelation>; car_models?:SingleOrArray<ModelRelation>; car_images?:ImageRelation[]|null };
type FinancingType = "credit"|"installment"|"credit_installment";
export type FinancingSummary={financingType:FinancingType;monthlyPayment:number;downPaymentPercent:number;termMonths:number;providerName:string;interestRate:number}|null;
export type CatalogVariant={id:string;name:string;slug:string;price:number;currency:string;old_price?:number|null;year:number;stock_status:string};
type NormalizedCar<T extends CarRelations>=Omit<T,"brands"|"car_models">&{brands:BrandRelation|null;car_models:ModelRelation|null;financing:FinancingSummary;variants:CatalogVariant[];modification_count:number};
function firstRelation<T>(relation:SingleOrArray<T>|undefined):T|null{return Array.isArray(relation)?relation[0]??null:relation??null}
function normalizeCar<T extends CarRelations>(car:T,financing:FinancingSummary=null):NormalizedCar<T>{return {...car,brands:firstRelation(car.brands),car_models:firstRelation(car.car_models),financing,variants:[],modification_count:1} as unknown as NormalizedCar<T>}
function monthlyPayment(principal:number,annualRate:number,months:number){if(principal<=0||months<=0)return 0;const rate=annualRate/100/12;return rate===0?Math.round(principal/months):Math.round((principal*rate)/(1-Math.pow(1+rate,-months)))}
function financingType(value:unknown):FinancingType{const type=String(value??"").toLowerCase();const credit=type.includes("credit")||type.includes("kredit")||type.includes("кредит");const installment=type.includes("install")||type.includes("rass")||type.includes("расс")||type.includes("muddat");return credit&&installment?"credit_installment":installment?"installment":"credit"}
function groupByModel<T extends CarRelations>(cars:Array<NormalizedCar<T>>):Array<NormalizedCar<T>>{const groups=new Map<string,Array<NormalizedCar<T>>>();for(const car of cars){const group=groups.get(car.model_id)??[];group.push(car);groups.set(car.model_id,group)}return [...groups.values()].map(group=>{const sorted=[...group].sort((a,b)=>Number(b.is_featured)-Number(a.is_featured)||(a.price??Number.MAX_SAFE_INTEGER)-(b.price??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name));const representative=sorted[0];return {...representative,variants:group.slice().sort((a,b)=>a.price-b.price||a.name.localeCompare(b.name)).map(v=>({id:v.id,name:v.name,slug:v.slug,price:Number(v.price),currency:v.currency,old_price:v.old_price??null,year:Number(v.year),stock_status:v.stock_status})),modification_count:group.length}})}
export class CatalogRepository{
 private readonly financing=new FinancingRepository();
 private async enrichFinancing<T extends CarRelations>(cars:T[]|null):Promise<Array<NormalizedCar<T>>>{if(!cars?.length)return[];return Promise.all(cars.map(async car=>{const programs=await this.financing.getApplicableProgramsForCar(car.id);const offers=(programs.data??[]).map(program=>{const termMonths=Math.max(1,Number(program.max_term_months??program.term_months??60));const downPaymentPercent=Math.min(100,Math.max(0,Number(program.min_down_payment_percent??program.down_payment_percent??0)));const interestRate=Math.max(0,Number(program.annual_interest_rate??program.interest_rate??0));const payment=monthlyPayment(Number(car.price)*(1-downPaymentPercent/100),interestRate,termMonths);const providerName=program.banks?.name_ru||program.banks?.name||program.name||"Moliyalashtirish";return{monthlyPayment:payment,downPaymentPercent,termMonths,providerName,financingType:financingType(program.financing_type??program.type),interestRate}}).filter(o=>o.monthlyPayment>0).sort((a,b)=>a.monthlyPayment-b.monthlyPayment||a.termMonths-b.termMonths);return normalizeCar(car,offers[0]??null)}))}
 async getCars(filters:CatalogQuery){const client=createPublicServerClient();let query=client.from("cars").select("id,model_id,name,slug,price,currency,old_price,year,body_type,fuel_type,transmission,drive_type,engine_volume,stock_status,is_featured,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))",{count:"exact"}).eq("is_active",true).in("stock_status",filters.status?[filters.status]:["available","coming_soon"]);if(filters.category){const category=await client.from("car_categories").select("id").eq("key",filters.category).eq("is_active",true).maybeSingle();if(category.error)return{...category,data:null};if(!category.data)return{data:[],count:0,error:null};const items=await client.from("car_category_items").select("car_id").eq("category_id",category.data.id);if(items.error)return{...items,data:null};const ids=(items.data??[]).map(item=>item.car_id);if(!ids.length)return{data:[],count:0,error:null};query=query.in("id",ids)}if(filters.brand)query=query.eq("brands.slug",filters.brand);if(filters.model)query=query.eq("car_models.slug",filters.model);if(filters.body)query=query.eq("body_type",filters.body);if(filters.fuel)query=query.eq("fuel_type",filters.fuel);if(filters.transmission)query=query.eq("transmission",filters.transmission);if(filters.drive)query=query.eq("drive_type",filters.drive);if(filters.minPrice!==undefined)query=query.gte("price",filters.minPrice);if(filters.maxPrice!==undefined)query=query.lte("price",filters.maxPrice);if(filters.minYear!==undefined)query=query.gte("year",filters.minYear);if(filters.maxYear!==undefined)query=query.lte("year",filters.maxYear);if(filters.sort==="price_asc")query=query.order("price",{ascending:true});else if(filters.sort==="price_desc")query=query.order("price",{ascending:false});else if(filters.sort==="newest")query=query.order("year",{ascending:false});else query=query.order("is_featured",{ascending:false}).order("created_at",{ascending:false});const result=await query;if(result.error)return{...result,data:null};let enriched=await this.enrichFinancing(result.data);if(filters.q)enriched=enriched.map(car=>({car,score:searchRelevance(filters.q!,[car.name,car.brands?.name??"",car.car_models?.name??"",car.slug])})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score).map(item=>item.car);const grouped=groupByModel(enriched);const from=(filters.page-1)*PAGE_SIZE;return{data:grouped.slice(from,from+PAGE_SIZE),count:grouped.length,error:null}}
 async getCarById(id:string){const result=await createPublicServerClient().from("cars").select("*,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("id",id).eq("is_active",true).single();return{...result,data:result.data?(await this.enrichFinancing([result.data]))[0]:null}}
 async getCarBySlug(slug:string){const result=await createPublicServerClient().from("cars").select("*,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("slug",slug).eq("is_active",true).single();return{...result,data:result.data?(await this.enrichFinancing([result.data]))[0]:null}}
 async getCarVariants(modelId:string){const result=await createPublicServerClient().from("cars").select("id,model_id,name,slug,price,currency,old_price,year,stock_status,is_featured,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("model_id",modelId).eq("is_active",true).in("stock_status",["available","coming_soon"]).order("price",{ascending:true});if(result.error)return{...result,data:null};return{...result,data:result.data??[]}}
 async getFeaturedCars(limit=4){const result=await createPublicServerClient().from("cars").select("id,model_id,name,slug,price,currency,year,stock_status,is_featured,body_type,fuel_type,transmission,engine_volume,brands(name,logo_url),car_models(name),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("is_active",true).eq("is_featured",true).order("created_at",{ascending:false}).limit(limit);return{...result,data:await this.enrichFinancing(result.data)}}
 async getAvailableCars(limit=4){const result=await createPublicServerClient().from("cars").select("id,model_id,name,slug,price,body_type,fuel_type,transmission,engine_volume,currency,year,stock_status,is_featured,brands(name,logo_url),car_models(name),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("is_active",true).eq("stock_status","available").order("created_at",{ascending:false}).limit(limit);return{...result,data:await this.enrichFinancing(result.data)}}
 async getActiveBrands(){const client=createPublicServerClient();const[brandsResult,modelsResult]=await Promise.all([client.from("brands").select("id,name,slug,logo_url").eq("is_active",true).order("name"),client.from("car_models").select("id,brand_id").eq("is_active",true)]);if(brandsResult.error)return brandsResult;if(modelsResult.error)return{...brandsResult,data:brandsResult.data?.map(brand=>({...brand,model_count:0}))??null};const modelCounts=new Map<string,number>();for(const model of modelsResult.data??[])if(model.brand_id)modelCounts.set(model.brand_id,(modelCounts.get(model.brand_id)??0)+1);return{...brandsResult,data:brandsResult.data?.map(brand=>({...brand,model_count:modelCounts.get(brand.id)??0}))??null}}
 async getModelsByBrand(brandSlug?:string){let query=createPublicServerClient().from("car_models").select("id,name,slug,brand_id,brands!inner(slug)").eq("is_active",true).order("name");if(brandSlug)query=query.eq("brands.slug",brandSlug);return query}
 async getBodyTypes(){return createPublicServerClient().from("cars").select("body_type").eq("is_active",true).not("body_type","is",null)}
 async getHomeCategories(){return createPublicServerClient().from("car_categories").select("id,key,name_uz,name_ru,icon,sort_order").eq("is_active",true).order("sort_order")}
 async getHomeBanners(){return createPublicServerClient().from("home_banners").select("id,title_uz,title_ru,description_uz,description_ru,image_url,cta_uz,cta_ru,href,sort_order").eq("is_active",true).order("sort_order")}
}
