import "server-only";
import { createPublicServerClient } from "@/supabase/public-server";
import { FinancingRepository } from "@/repositories/financing-repository";
import { PAGE_SIZE, type CatalogQuery } from "@/features/catalog/catalog-query";
import { searchRelevance } from "@/features/catalog/search-utils";

type SingleOrArray<T> = T | T[] | null;
type BrandRelation = { name: string; slug?: string | null; logo_url?: string | null };
type ModelRelation = { name: string; slug?: string | null };
type ColorRelation = { id: string; name_uz: string; name_ru: string; hex_code: string };
type ImageRelation = { public_url: string | null; alt_text: string | null; is_primary: boolean; sort_order: number; color_id?: string | null; car_colors?: SingleOrArray<ColorRelation> };
type CarRelations = { brands?: SingleOrArray<BrandRelation>; car_models?: SingleOrArray<ModelRelation>; car_images?: ImageRelation[] | null };
export type FinancingSummary = { financingType: "credit" | "installment" | "credit_installment"; monthlyPayment: number; downPaymentPercent: number; termMonths: number; providerName: string; interestRate: number } | null;
type NormalizedCar<T extends CarRelations> = Omit<T, "brands" | "car_models"> & { id: string; slug: string; name: string; price: number; currency: string; year: number; stock_status: string; is_featured: boolean; brands: BrandRelation | null; car_models: ModelRelation | null; financing: FinancingSummary };
function firstRelation<T>(relation: SingleOrArray<T> | undefined): T | null { if (Array.isArray(relation)) return relation[0] ?? null; return relation ?? null; }
function normalizeCar<T extends CarRelations>(car: T, financing: FinancingSummary = null): NormalizedCar<T> { return { ...car, brands: firstRelation(car.brands), car_models: firstRelation(car.car_models), financing } as unknown as NormalizedCar<T>; }
function normalizeCars<T extends CarRelations>(cars: T[] | null): Array<NormalizedCar<T>> | null { return cars?.map((car) => normalizeCar(car)) ?? null; }
function monthlyPayment(principal: number, annualRate: number, months: number) { if (principal <= 0 || months <= 0) return 0; const r = annualRate / 100 / 12; return r === 0 ? Math.round(principal / months) : Math.round((principal * r) / (1 - Math.pow(1 + r, -months))); }
function financingType(value: unknown): FinancingSummary extends infer F ? F extends { financingType: infer T } ? T : never : never { const type = String(value ?? "").toLowerCase(); const credit = type.includes("credit") || type.includes("kredit") || type.includes("кредит"); const installment = type.includes("install") || type.includes("rass") || type.includes("расс") || type.includes("muddat"); return (credit && installment ? "credit_installment" : installment ? "installment" : "credit") as never; }

export class CatalogRepository {
  private readonly financing = new FinancingRepository();
  private async enrichFinancing<T extends CarRelations>(cars: T[] | null) { if (!cars?.length) return [] as Array<NormalizedCar<T>>; return Promise.all(cars.map(async (car) => { const programs = await this.financing.getApplicableProgramsForCar(car.id); const offers = (programs.data ?? []).map((p) => { const months = Math.max(1, Number(p.max_term_months ?? p.term_months ?? 60)); const down = Math.min(100, Math.max(0, Number(p.min_down_payment_percent ?? p.down_payment_percent ?? 0))); const rate = Math.max(0, Number(p.annual_interest_rate ?? p.interest_rate ?? 0)); const payment = monthlyPayment(Number(car.price) * (1 - down / 100), rate, months); return { monthlyPayment: payment, downPaymentPercent: down, termMonths: months, providerName: p.banks?.name ?? p.dealers?.name ?? p.name ?? "Moliyalashtirish", financingType: financingType(p.financing_type ?? p.type), interestRate: rate }; }).filter((o) => o.monthlyPayment > 0).sort((a,b) => a.monthlyPayment-b.monthlyPayment || a.termMonths-b.termMonths); return normalizeCar(car, offers[0] ?? null); })); }
  async getCars(filters: CatalogQuery) { const from=(filters.page-1)*PAGE_SIZE; const client=createPublicServerClient(); let query=client.from("cars").select("id,name,slug,price,currency,old_price,year,body_type,fuel_type,transmission,drive_type,engine_volume,stock_status,is_featured,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))",{count:"exact"}).eq("is_active",true).in("stock_status",filters.status?[filters.status]:["available","coming_soon"]); if(filters.category){const category=await client.from("car_categories").select("id").eq("key",filters.category).eq("is_active",true).maybeSingle();if(category.error)return{...category,data:null};if(!category.data)return{data:[],count:0,error:null};const items=await client.from("car_category_items").select("car_id").eq("category_id",category.data.id);if(items.error)return{...items,data:null};const ids=(items.data??[]).map(i=>i.car_id);if(!ids.length)return{data:[],count:0,error:null};query=query.in("id",ids);} if(filters.brand)query=query.eq("brands.slug",filters.brand);if(filters.model)query=query.eq("car_models.slug",filters.model);if(filters.body)query=query.eq("body_type",filters.body);if(filters.fuel)query=query.eq("fuel_type",filters.fuel);if(filters.transmission)query=query.eq("transmission",filters.transmission);if(filters.drive)query=query.eq("drive_type",filters.drive);if(filters.minPrice!==undefined)query=query.gte("price",filters.minPrice);if(filters.maxPrice!==undefined)query=query.lte("price",filters.maxPrice);if(filters.minYear!==undefined)query=query.gte("year",filters.minYear);if(filters.maxYear!==undefined)query=query.lte("year",filters.maxYear);if(filters.sort==="price_asc")query=query.order("price",{ascending:true});else if(filters.sort==="price_desc")query=query.order("price",{ascending:false});else if(filters.sort==="newest")query=query.order("year",{ascending:false});else query=query.order("is_featured",{ascending:false}).order("created_at",{ascending:false}); if(filters.q){const result=await query;if(result.error)return{...result,data:null};const enriched=await this.enrichFinancing(result.data);const ranked=enriched.map(car=>({car,score:searchRelevance(filters.q!,[car.name,car.brands?.name??"",car.car_models?.name??"",car.slug])})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.car);return{data:ranked.slice(from,from+PAGE_SIZE),count:ranked.length,error:null};}const result=await query.range(from,from+PAGE_SIZE-1);return{...result,data:await this.enrichFinancing(result.data)}; }
  async getCarById(id:string){const result=await createPublicServerClient().from("cars").select("*,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("id",id).eq("is_active",true).single();const data=result.data?[...(await this.enrichFinancing([result.data]))][0]:null;return{...result,data};}
  async getCarBySlug(slug:string){const result=await createPublicServerClient().from("cars").select("*,brands(name,slug,logo_url),car_models(name,slug),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("slug",slug).eq("is_active",true).single();const data=result.data?[...(await this.enrichFinancing([result.data]))][0]:null;return{...result,data};}
  async getFeaturedCars(limit=4){const result=await createPublicServerClient().from("cars").select("id,name,slug,price,currency,year,stock_status,is_featured,body_type,fuel_type,transmission,engine_volume,brands(name,logo_url),car_models(name),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("is_active",true).eq("is_featured",true).order("created_at",{ascending:false}).limit(limit);return{...result,data:await this.enrichFinancing(result.data)};}
  async getAvailableCars(limit=4){const result=await createPublicServerClient().from("cars").select("id,name,slug,price,currency,year,stock_status,is_featured,body_type,fuel_type,transmission,engine_volume,brands(name,logo_url),car_models(name),car_images(public_url,alt_text,is_primary,sort_order,color_id,car_colors(id,name_uz,name_ru,hex_code))").eq("is_active",true).eq("stock_status","available").order("created_at",{ascending:false}).limit(limit);return{...result,data:await this.enrichFinancing(result.data)};}
  async getActiveBrands(){const client=createPublicServerClient();const[brandsResult,modelsResult]=await Promise.all([client.from("brands").select("id,name,slug,logo_url").eq("is_active",true).order("name"),client.from("car_models").select("id,brand_id").eq("is_active",true)]);if(brandsResult.error)return brandsResult;if(modelsResult.error)return{...brandsResult,data:brandsResult.data?.map(b=>({...b,model_count:0}))??null};const counts=new Map<string,number>();for(const model of modelsResult.data??[])if(model.brand_id)counts.set(model.brand_id,(counts.get(model.brand_id)??0)+1);return{...brandsResult,data:brandsResult.data?.map(b=>({...b,model_count:counts.get(b.id)??0}))??null};}
  async getModelsByBrand(brandSlug?:string){let query=createPublicServerClient().from("car_models").select("id,name,slug,brand_id,brands!inner(slug)").eq("is_active",true).order("name");if(brandSlug)query=query.eq("brands.slug",brandSlug);return query;}
  async getBodyTypes(){return createPublicServerClient().from("cars").select("body_type").eq("is_active",true).not("body_type","is",null);}
  async getHomeCategories(){return createPublicServerClient().from("car_categories").select("id,key,name_uz,name_ru,icon,sort_order").eq("is_active",true).order("sort_order");}
  async getHomeBanners(){return createPublicServerClient().from("home_banners").select("id,title_uz,title_ru,description_uz,description_ru,image_url,cta_uz,cta_ru,href,sort_order").eq("is_active",true).order("sort_order");}
}
