import "server-only";
import { AdminOrderRepository, type AdminOrderFilters, type Overrides } from "@/repositories/admin-order-repository";
import { updateOrderStatusInputSchema } from "@/schemas/admin-order";
import type { OrderStatus, PurchaseType } from "@/types/domain";
const ORDER_STATUSES:OrderStatus[]=["pending","confirmed","processing","completed","cancelled"];const PURCHASE_TYPES:PurchaseType[]=["cash","online","credit","installment"];
const ALLOWED:Record<OrderStatus,OrderStatus[]>={pending:["confirmed","cancelled"],confirmed:["processing","cancelled"],processing:["completed","cancelled"],completed:[],cancelled:[]};
const isStatus=(v:string|undefined):v is OrderStatus=>!!v&&(ORDER_STATUSES as string[]).includes(v);const isPurchase=(v:string|undefined):v is PurchaseType=>!!v&&(PURCHASE_TYPES as string[]).includes(v);const parseDate=(v:string|undefined)=>{if(!v)return undefined;const d=new Date(v);return Number.isNaN(d.getTime())?undefined:d.toISOString();};
const text=(v:unknown,max:number)=>typeof v==="string"?v.trim().slice(0,max):undefined;const num=(v:unknown,min:number,max:number)=>{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:undefined;};
export class AdminOrderService{constructor(private readonly repository=new AdminOrderRepository()){}listOrders(filters:{status?:string;purchaseType?:string;dateFrom?:string;dateTo?:string;needsAttention?:boolean}){const normalized:AdminOrderFilters={status:isStatus(filters.status)?filters.status:undefined,purchaseType:isPurchase(filters.purchaseType)?filters.purchaseType:undefined,dateFrom:parseDate(filters.dateFrom),dateTo:parseDate(filters.dateTo),needsAttention:filters.needsAttention===true};return this.repository.listOrders(normalized);}findById(orderId:string){return this.repository.findById(orderId);}async updateStatus(input:unknown,actorId:string){const{orderId,newStatus}=updateOrderStatusInputSchema.parse(input);const order=await this.repository.findById(orderId);if(!order.data)throw new Error("Buyurtma topilmadi.");const current=order.data.status;if(current===newStatus)return order.data;if(!(ALLOWED[current]??[]).includes(newStatus))throw new Error("Bu holatga o'tish mumkin emas.");const updated=await this.repository.updateStatusIfCurrent(orderId,current,newStatus);if(updated.error||!updated.data)throw new Error("Buyurtma holati boshqa administrator tomonidan o'zgartirilgan. Sahifani yangilang.");const history=await this.repository.createStatusHistory({orderId,oldStatus:current,newStatus,changedBy:actorId});if(history.error)throw new Error("Buyurtma tarixini saqlab bo'lmadi.");await this.repository.audit(actorId,"order.status_updated","order",orderId,{oldStatus:current,newStatus});return updated.data;}
async updateManagerOrder(input:Record<string,unknown>,actorId:string){const orderId=text(input.orderId,100);if(!orderId)throw new Error("Buyurtma identifikatori noto'g'ri.");const current=await this.repository.findById(orderId);if(!current.data)throw new Error("Buyurtma topilmadi.");const old=current.data;const oldOv=old.managerOverrides??{};const overrides:Overrides={customer:{fullName:text(input.fullName,160),phone:text(input.phone,40)},car:{color:text(input.color,80)},finance:{downPaymentPercent:num(input.downPaymentPercent,0,100),downPaymentAmount:num(input.downPaymentAmount,0,2_000_000_000_000),financedAmount:num(input.financedAmount,0,2_000_000_000_000),interestRate:num(input.interestRate,0,100),termMonths:num(input.termMonths,1,120)},notes:text(input.notes,2000)};Object.keys(overrides).forEach(k=>{const v=(overrides as Record<string,unknown>)[k];if(v&&typeof v==="object")Object.keys(v as Record<string,unknown>).forEach(x=>{if((v as Record<string,unknown>)[x]===undefined)delete(v as Record<string,unknown>)[x];});if(v&&typeof v==="object"&&!Object.keys(v as object).length)delete(overrides as Record<string,unknown>)[k];});const updated=await this.repository.updateManagerOverrides(orderId,overrides,actorId);if(updated.error||!updated.data)throw new Error("Buyurtma ma'lumotlarini saqlab bo'lmadi.");const changed:Record<string,{old:unknown;new:unknown}>={};const flat=(prefix:string,a:unknown,b:unknown)=>{if(JSON.stringify(a)!==JSON.stringify(b))changed[prefix]={old:a??null,new:b??null};};flat("customer.fullName",oldOv.customer?.fullName,overrides.customer?.fullName);flat("customer.phone",oldOv.customer?.phone,overrides.customer?.phone);flat("car.color",oldOv.car?.color,overrides.car?.color);flat("finance.downPaymentPercent",oldOv.finance?.downPaymentPercent,overrides.finance?.downPaymentPercent);flat("finance.downPaymentAmount",oldOv.finance?.downPaymentAmount,overrides.finance?.downPaymentAmount);flat("finance.financedAmount",oldOv.finance?.financedAmount,overrides.finance?.financedAmount);flat("finance.interestRate",oldOv.finance?.interestRate,overrides.finance?.interestRate);flat("finance.termMonths",oldOv.finance?.termMonths,overrides.finance?.termMonths);flat("notes",oldOv.notes,overrides.notes);if(Object.keys(changed).length)await this.repository.audit(actorId,"order.manager_edited","order",orderId,{changed});return updated.data;}}
