import "server-only";
import { submitCreditApplicationInputSchema, syncApplicationStatusInputSchema, providerSubmissionResponseSchema, providerStatusResponseSchema } from "@/schemas/credit-application";
import { CreditApplicationRepository } from "@/repositories/credit-application-repository";
import { OrderService } from "@/services/order-service";
import { AdminOrderService } from "@/services/admin-order-service";
import { FinancingService } from "@/services/financing-service";
import { getBankProviderRegistry } from "@/services/banks/bank-registry-bootstrap";
import { SmsService } from "@/services/sms/sms-service";
import { MockSmsProvider } from "@/services/sms/providers/mock-sms-provider";
import type { OrderStatus } from "@/types/domain";

type Bank={id:string;code:string;is_active:boolean;integration_status:string};
const firstBank=(r:Bank|Bank[]|null|undefined):Bank|null=>Array.isArray(r)?r[0]??null:r??null;
const TERMINAL_STATUSES=new Set(["approved","rejected","cancelled","failed"]);
const submissionStatus=(s:string)=>{const v=s.trim().toLowerCase();if(v==="pending")return "submitted";if(["submitted","approved","rejected","cancelled"].includes(v))return v;return null;};
const syncStatus=(s:string)=>{const v=s.trim().toLowerCase();if(v==="pending")return "no_change";if(["approved","rejected","cancelled"].includes(v))return v;return null;};
export type SubmitApplicationResult={outcome:"submitted"|"already_exists";applicationId:string;status:string};
export type SyncApplicationStatusResult={applicationId:string;orderId:string;status:string};
export class CreditApplicationService{
 constructor(private readonly applications=new CreditApplicationRepository(),private readonly orders=new OrderService(),private readonly financing=new FinancingService(),private readonly sms=new SmsService(new MockSmsProvider()),private readonly adminOrders=new AdminOrderService()){}
 async submitApplication(input:unknown,customerId:string):Promise<SubmitApplicationResult>{const {orderId,financingProgramId}=submitCreditApplicationInputSchema.parse(input);const orderResult=await this.orders.findByIdForCustomer(orderId,customerId);if(!orderResult.data)throw new Error("Buyurtma topilmadi yoki sizga tegishli emas");const order=orderResult.data;if(order.purchase_type!=="credit"&&order.purchase_type!=="installment")throw new Error("Bu buyurtma kredit yoki bo'lib to'lash turi emas");const existing=await this.applications.findByOrderId(orderId);if(existing.data)return{outcome:"already_exists",applicationId:existing.data.id,status:existing.data.status};const program=await this.financing.getProgramById(financingProgramId);if(!program.data||!program.data.is_active)throw new Error("Kredit dasturi topilmadi yoki faol emas");const bank=firstBank(program.data.banks as Bank|Bank[]|null);if(!bank||!bank.is_active)throw new Error("Bank faol emas");if(bank.integration_status!=="connected")throw new Error("Bu bank orqali onlayn ariza yuborib bo'lmaydi");let provider;try{provider=getBankProviderRegistry().get(bank.code);}catch{throw new Error("Bank integratsiyasi hozircha mavjud emas");}let raw:unknown;try{raw=await provider.submitCreditApplication({orderId});}catch{throw new Error("Bankka ariza yuborish vaqtincha mavjud emas");}const parsed=providerSubmissionResponseSchema.safeParse(raw);if(!parsed.success)throw new Error("Bankdan noto'g'ri javob qaytdi");const status=submissionStatus(parsed.data.status);if(!status)throw new Error("Bankdan noma'lum ariza holati qaytdi");const created=await this.applications.create({orderId,bankId:bank.id,financingProgramId,externalApplicationId:parsed.data.externalApplicationId,status});if(created.error||!created.data)throw new Error("Arizani saqlab bo'lmadi");return{outcome:"submitted",applicationId:created.data.id,status:created.data.status};}
 async syncApplicationStatus(input:unknown,customerId:string,customerPhone:string|null):Promise<SyncApplicationStatusResult>{const {applicationId}=syncApplicationStatusInputSchema.parse(input);const app=await this.applications.findById(applicationId);if(!app.data)throw new Error("Ariza topilmadi");const order=await this.orders.findByIdForCustomer(app.data.order_id,customerId);if(!order.data)throw new Error("Ariza topilmadi yoki sizga tegishli emas");return this.performSync(app.data,{id:order.data.id,status:order.data.status as OrderStatus,orderNumber:order.data.order_number},customerPhone);}
 async syncApplicationStatusAsAdmin(input:unknown):Promise<SyncApplicationStatusResult>{const {applicationId}=syncApplicationStatusInputSchema.parse(input);const app=await this.applications.findById(applicationId);if(!app.data)throw new Error("Ariza topilmadi");const order=await this.adminOrders.findById(app.data.order_id);if(!order.data)throw new Error("Ariza topilmadi");return this.performSync(app.data,{id:order.data.id,status:order.data.status,orderNumber:order.data.orderNumber},order.data.customer?.phone??null);}
 private async performSync(app:{id:string;order_id:string;status:string;financing_program_id:string|null;external_application_id:string|null},order:{id:string;status:OrderStatus;orderNumber:string},customerPhone:string|null):Promise<SyncApplicationStatusResult>{if(TERMINAL_STATUSES.has(app.status))return{applicationId:app.id,orderId:app.order_id,status:app.status};if(!app.financing_program_id)throw new Error("Holatni yangilab bo'lmadi");const program=await this.financing.getProgramById(app.financing_program_id);if(!program.data)throw new Error("Holatni yangilab bo'lmadi");const bank=firstBank(program.data.banks as Bank|Bank[]|null);if(!bank||bank.integration_status!=="connected")throw new Error("Bank integratsiyasi hozircha mavjud emas");if(!app.external_application_id)throw new Error("Ariza hali bank tomonidan qabul qilinmagan");let provider;try{provider=getBankProviderRegistry().get(bank.code);}catch{throw new Error("Bank integratsiyasi hozircha mavjud emas");}let raw:unknown;try{raw=await provider.getApplicationStatus(app.external_application_id);}catch{throw new Error("Holatni tekshirish vaqtincha mavjud emas. Birozdan keyin qayta urinib ko'ring.");}const parsed=providerStatusResponseSchema.safeParse(raw);if(!parsed.success)throw new Error("Bankdan noto'g'ri javob qaytdi");const mapped=syncStatus(parsed.data.status);if(!mapped)throw new Error("Bankdan noto'g'ri javob qaytdi");if(mapped==="no_change")return{applicationId:app.id,orderId:app.order_id,status:app.status};const updated=await this.applications.updateStatus(app.id,mapped);if(updated.error||!updated.data)throw new Error("Holatni saqlab bo'lmadi");if(mapped==="approved"){try{await this.orders.advanceToConfirmedIfPending(order.id,order.status);}catch{}}if((mapped==="approved"||mapped==="rejected")&&customerPhone){try{await this.sms.sendMessage(customerPhone,mapped==="approved"?`Buyurtmangiz uchun kredit arizasi tasdiqlandi. Buyurtma: ${order.orderNumber}.`:`Buyurtmangiz uchun kredit arizasi rad etildi. Buyurtma: ${order.orderNumber}.`);}catch{}}return{applicationId:updated.data.id,orderId:app.order_id,status:updated.data.status};}
 async cancelIfNonTerminal(orderId:string){const app=await this.applications.findByOrderId(orderId);if(!app.data||TERMINAL_STATUSES.has(app.data.status))return;if(!app.data.external_application_id)return; if(!app.data.financing_program_id)return;const program=await this.financing.getProgramById(app.data.financing_program_id);if(!program.data)return;const bank=firstBank(program.data.banks as Bank|Bank[]|null);if(!bank||!bank.is_active||bank.integration_status!=="connected")return;let provider;try{provider=getBankProviderRegistry().get(bank.code);}catch{return;}try{await provider.cancelApplication(app.data.external_application_id);}catch{return;}await this.applications.updateStatus(app.data.id,"cancelled");}
}
