"use server";
import { revalidatePath } from "next/cache";
import { ZodError } from "zod";
import { getCurrentCustomer } from "@/lib/customer-session";
import { CreditApplicationService } from "@/services/credit-application-service";
const text = (formData: FormData, key: string) => { const value = formData.get(key); return typeof value === "string" && value.trim() ? value.trim() : null; };
export type SubmitCreditApplicationResult = { status: "submitted"; applicationId: string } | { status: "already_exists"; applicationId: string; applicationStatus: string } | { status: "error"; message: string };
export type SyncCreditApplicationStatusResult = { status: "ok"; applicationStatus: string } | { status: "error"; message: string };
export async function submitCreditApplicationAction(formData: FormData): Promise<SubmitCreditApplicationResult> { const customer = await getCurrentCustomer(); if (!customer) return { status: "error", message: "Ariza yuborish uchun avval tasdiqlashdan o'ting" }; const orderId = text(formData, "orderId"); const financingProgramId = text(formData, "financingProgramId"); if (!orderId || !financingProgramId) return { status: "error", message: "So'rov yaroqsiz" }; try { const result = await new CreditApplicationService().submitApplication({ orderId, financingProgramId }, customer.id); revalidatePath(`/account/orders/${orderId}`); if (result.outcome === "already_exists") return { status: "already_exists", applicationId: result.applicationId, applicationStatus: result.status }; return { status: "submitted", applicationId: result.applicationId }; } catch (error) { if (error instanceof ZodError) return { status: "error", message: "So'rov yaroqsiz" }; return { status: "error", message: error instanceof Error ? error.message : "Ariza yuborib bo'lmadi" }; } }
export async function syncCreditApplicationStatusAction(formData: FormData): Promise<SyncCreditApplicationStatusResult> { const customer = await getCurrentCustomer(); if (!customer) return { status: "error", message: "Holatni yangilash uchun avval tasdiqlashdan o'ting" }; const applicationId = text(formData, "applicationId"); if (!applicationId) return { status: "error", message: "So'rov yaroqsiz" }; try { const result = await new CreditApplicationService().syncApplicationStatus({ applicationId }, customer.id, customer.phone); revalidatePath(`/account/orders/${result.orderId}`); return { status: "ok", applicationStatus: result.status }; } catch (error) { if (error instanceof ZodError) return { status: "error", message: "So'rov yaroqsiz" }; return { status: "error", message: error instanceof Error ? error.message : "Holatni yangilab bo'lmadi" }; } }
