import Link from "next/link";
import { Header, Footer } from "@/components/site-chrome";
import { EmptyState } from "@/components/catalog-ui";
import { HomeFinancingGrid } from "@/components/home-financing-grid";
import { CatalogService } from "@/services/catalog-service";
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const metadata = { title: "Cardrive.uz | Yangi avtomobillar", description: "O‘zbekistondagi yangi avtomobillar katalogi." };
export default async function HomePage(){const service=new CatalogService();const[featured,available,brands]=await Promise.all([service.getFeaturedCars(),service.getAvailableCars(),service.getActiveBrands()]);return <><Header/><main><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20"><p className="text-sm font-semibold text-amber-400">Yangi avtomobillar marketplace’i</p><h1 className="mt-4 text-4xl font-black sm:text-6xl">Yangi avtomobilingizni ishonch bilan tanlang.</h1><p className="mt-5 max-w-xl text-lg text-slate-300">Brendlar, texnik xususiyatlar va shaffof narxlarni bir joyda solishtiring.</p><div className="mt-8 flex gap-3"><Link href="/cars" className="rounded-full bg-amber-500 px-5 py-3 font-bold text-slate-950">Avtomobillarni ko‘rish</Link><Link href="/cars?sort=featured" className="rounded-full border border-slate-600 px-5 py-3 font-bold">Tavsiya etilganlar</Link></div></div></section><section className="mx-auto max-w-7xl px-5 py-16"><div className="flex items-end justify-between"><div><p className="text-sm font-bold text-amber-600">TANLANGANLAR</p><h2 className="mt-2 text-3xl font-black">Tavsiya etilgan avtomobillar</h2></div><Link href="/cars?sort=featured" className="text-sm font-bold underline">Barchasi</Link></div><div className="mt-7">{featured.data?.length?<HomeFinancingGrid cars={featured.data}/>:<EmptyState title="Hozircha tavsiya etilgan avtomobillar yo‘q" action="Katalogga o‘tish"/>}</div></section><section className="bg-white"><div className="mx-auto max-w-7xl px-5 py-16"><h2 className="text-3xl font-black">Mavjud avtomobillar</h2><div className="mt-7">{available.data?.length?<HomeFinancingGrid cars={available.data}/>:<EmptyState title="Hozircha mavjud avtomobillar yo‘q"/>}</div></div></section><section className="mx-auto max-w-7xl px-5 py-16"><h2 className="text-3xl font-black">Brendlar</h2>{brands.data?.length?<div className="mt-6 flex flex-wrap gap-3">{brands.data.map(brand=><Link key={brand.id} href={"/cars?brand="+brand.slug} className="rounded-xl border border-slate-200 bg-white px-5 py-4 font-bold">{brand.name}</Link>)}</div>:<EmptyState title="Hozircha faol brendlar yo‘q"/>}</section></main><Footer/></>}
