import Link from "next/link";
import { signOutAction } from "@/app/admin/sign-out-action";

export function AdminShell({ children }: { children: React.ReactNode }) {
  return <div className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[260px_1fr]"><aside className="border-b bg-slate-950 p-5 text-white lg:min-h-screen lg:border-r lg:border-b-0"><Link href="/admin" className="text-lg font-black">CARDRIVE <span className="text-amber-400">ADMIN</span></Link><nav className="mt-6 flex gap-3 overflow-x-auto text-sm lg:flex-col"><Link href="/admin">Dashboard</Link><Link href="/admin/orders">Buyurtmalar</Link><Link href="/admin/customers">Mijozlar</Link><Link href="/admin/brands">Brendlar</Link><Link href="/admin/models">Modellar</Link><Link href="/admin/cars">Avtomobillar</Link><Link href="/admin/categories">Kategoriyalar</Link><Link href="/admin/banners">Bannerlar</Link></nav></aside><div><header className="flex items-center justify-between border-b bg-white px-5 py-4"><p className="text-sm font-semibold text-slate-600">Boshqaruv paneli</p><form action={signOutAction}><button className="rounded-full border px-3 py-1.5 text-sm">Chiqish</button></form></header><main className="p-5 sm:p-8">{children}</main></div></div>;
}
export function AdminCard({ label, value }: { label: string; value: number | string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>; }
export function AdminTable({ children }: { children: React.ReactNode }) { return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm">{children}</table></div>; }
export function SlugHint() { return <p className="text-xs text-slate-500">Slug nomdan tavsiya etiladi; noyob bo‘lishi kerak.</p>; }
export function Field({ name, label, type = "text", required = false, defaultValue }: { name: string; label: string; type?: string; required?: boolean; defaultValue?: string | number }) { return <label className="block text-sm font-semibold text-slate-700">{label}<input name={name} type={type} required={required} defaultValue={defaultValue} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label>; }
