"use client";
import { useState } from "react";

type Props={initialFuelType?:string|null;initialEngineType?:string|null;initialBatteryCapacityKwh?:number|null;initialAcceleration0100Sec?:number|null;initialChargingTimeMinutes?:number|null;initialRangeKm?:number|null;initialEngineVolume?:number|null;initialEnginePower?:number|null;initialTransmission?:string|null;initialDriveType?:string|null};
const Field=({name,label,type="text",defaultValue,step}:{name:string;label:string;type?:string;defaultValue?:string|number|null;step?:string})=><label className="text-sm font-semibold">{label}<input name={name} type={type} step={step} defaultValue={defaultValue??""} className="mt-1 w-full rounded-lg border p-2"/></label>;
export function CarSpecsFields(p:Props){const [fuel,setFuel]=useState(p.initialFuelType??"");const electric=fuel.toLowerCase().includes("elektr");const hybrid=fuel.toLowerCase().includes("gibrid")||fuel.toLowerCase().includes("hybrid");return <>
<label className="text-sm font-semibold">Yoqilg‘i <span className="text-red-600">*</span><select name="fuelType" required value={fuel} onChange={e=>setFuel(e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Tanlang</option><option value="Benzin">Benzin</option><option value="Dizel">Dizel</option><option value="Elektr">Elektr</option><option value="Gibrid">Gibrid</option><option value="Gaz">Gaz</option></select></label>
{!electric&&<><Field name="engineVolume" label="Dvigatel hajmi" type="number" step="0.1" defaultValue={p.initialEngineVolume}/><Field name="engineType" label="Dvigatel turi (Turbo / Atmosfera)" defaultValue={p.initialEngineType}/><Field name="enginePower" label="Quvvat" type="number" defaultValue={p.initialEnginePower}/><Field name="transmission" label="Transmissiya" defaultValue={p.initialTransmission}/><Field name="driveType" label="Yuritma" defaultValue={p.initialDriveType}/></>}
{(electric||hybrid)&&<><Field name="batteryCapacityKwh" label="Batareya sig‘imi (kWh)" type="number" step="0.1" defaultValue={p.initialBatteryCapacityKwh}/><Field name="rangeKm" label="Elektr yurish masofasi (km)" type="number" defaultValue={p.initialRangeKm}/></>}
{electric&&<><Field name="acceleration0100Sec" label="0–100 km/soat (sekund)" type="number" step="0.1" defaultValue={p.initialAcceleration0100Sec}/><Field name="chargingTimeMinutes" label="Tezkor zaryadlash vaqti (minut)" type="number" defaultValue={p.initialChargingTimeMinutes}/><Field name="enginePower" label="Quvvat (kW)" type="number" defaultValue={p.initialEnginePower}/><Field name="driveType" label="Yuritma" defaultValue={p.initialDriveType}/></>}
</>}
