import Link from "next/link";
import { formatPrice, stockLabel } from "@/lib/formatters";
type Car = { slug: string; name: string; price: number; currency: string; year: number; stock_status: string; is_featured: boolean; body_type?: string | null; transmission?: string | null; brands?: { name: string } | null; car_models?: { name: string } | null; car_images?: Array<{ public_url: string | null; alt_text: string | null; is_primary: boolean; sort_order: number }> | null; };
function imageFor(car: Car) { return [...(car.car_images ?? [])].sort((a,b) => Number(b.is_primary)-Number(a.is_primary) || a.sort_order-b.sort_order)[0]?.public_url; }
export function AvailabilityBadge({ status }: { status: string }) { const tone=status==="available" ? "bg-emerald-50 text-emerald-700" : status==="coming_soon" ? "bg-amber-50 text-amber-700" : "bg-slate-100 text-slate-700"; return <span className={"rounded-full px-2.5 py-1 text-xs font-semibold "+tone}>{stockLabel(status)}</span>; }
export function Price({ amount, currency }: { amount: number; currency: string }) { return <p className="text-xl font-bold tracking-tight text-slate-950">{formatPrice(amount,currency)}</p>; }
export function CarCard({ car }: { car: Car }) { const image=imageFor(car); return <Link href={"/cars/"+car.slug} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative aspect-[16/10] bg-slate-200">{image ? <img src={image} alt={car.car_images?.[0]?.alt_text ?? car.name} className="h-full w-full object-cover" loading="lazy" /> : <div className="flex h-full items-center justify-center text-sm font-medium text-slate-500">Rasm tez orada</div>}{car.is_featured && <span className="absolute left-3 top-3 rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">Tavsiya</span>}</div><div className="space-y-3 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{car.brands?.name}</p><h3 className="mt-1 text-lg font-bold text-slate-950">{car.name}</h3></div><AvailabilityBadge status={car.stock_status}/></div><p className="text-sm text-slate-600">{[car.year,car.body_type,car.transmission].filter(Boolean).join(" · ")}</p><Price amount={car.price} currency={car.currency}/></div></Link>; }
export function CarGrid({ cars }: { cars: Car[] }) { return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{cars.map((car)=><CarCard key={car.slug} car={car}/>)}</div>; }
export function EmptyState({ title, actionHref="/cars", action="Filtrlarni tozalash" }: { title: string; actionHref?: string; action?: string }) { return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">{title}</h2><Link href={actionHref} className="mt-4 inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">{action}</Link></section>; }
export function CatalogSkeleton() { return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6},(_,i)=><div key={i} className="h-80 animate-pulse rounded-2xl bg-slate-200"/>)}</div>; }
