import Link from "next/link";
import { formatPrice, stockLabel } from "@/lib/formatters";
type Car = { slug:string; name:string; price:number; currency:string; year:number; stock_status:string; is_featured:boolean; body_type?:string|null; transmission?:string|null; brands?:{name:string; slug?:string|null; logo_url?:string|null}|null; car_models?:{name:string}|null; car_images?:Array<{public_url:string|null;alt_text:string|null;is_primary:boolean;sort_order:number}>|null };
function imageFor(car:Car){return [...(car.car_images??[])].sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order)[0]?.public_url;}
function brandLogoFor(car:Car){const url=car.brands?.logo_url?.trim();return url||null;}
export function AvailabilityBadge({status}:{status:string}){const tone=status==="available"?"bg-emerald-50 text-emerald-700":status==="coming_soon"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700";return <span className={"rounded-full px-2.5 py-1 text-xs font-semibold "+tone}>{stockLabel(status)}</span>}
export function Price({amount,currency}:{amount:number;currency:string}){return <p className="text-xl font-bold tracking-tight text-slate-950">{formatPrice(amount,currency)}</p>}
export function CarCard({car}:{car:Car}){const image=imageFor(car);const logoUrl=brandLogoFor(car);const brandName=car.brands?.name??"";return <Link href={"/cars/"+car.slug} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative flex aspect-[16/10] items-center justify-center bg-white px-4 pt-12">{image?<img src={image} alt={car.car_images?.[0]?.alt_text??car.name} className="h-full w-full object-contain" loading="lazy"/>:<div className="flex h-full w-full items-center justify-center rounded-xl bg-slate-100 text-sm font-medium text-slate-500">Rasm tez orada</div>}{logoUrl?<div className="absolute left-3 top-3 flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm" title={brandName}><img src={logoUrl} alt={brandName} className="h-full w-full object-contain" loading="eager" decoding="async" referrerPolicy="no-referrer"/></div>:<div className="absolute left-3 top-3 flex h-10 items-center gap-2 rounded-xl border border-slate-200 bg-white px-2.5 shadow-sm"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-slate-100 text-[9px] font-bold text-slate-500">{brandName.slice(0,2).toUpperCase()||"?"}</span>{brandName&&<span className="text-[10px] font-bold uppercase text-slate-600">{brandName}</span>}</div>}{car.is_featured&&<span className="absolute right-3 top-3 rounded-full bg-slate-950 px-2.5 py-1 text-xs font-semibold text-white">Tavsiya</span>}</div><div className="space-y-2 p-4 pt-3 text-center"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{brandName}</p><h3 className="text-lg font-bold text-slate-950">{car.name}</h3><Price amount={car.price} currency={car.currency}/><div className="flex flex-wrap items-center justify-center gap-2 pt-1"><AvailabilityBadge status={car.stock_status}/>{[car.year,car.body_type,car.transmission].filter(Boolean).length>0&&<span className="text-xs text-slate-500">{[car.year,car.body_type,car.transmission].filter(Boolean).join(" · ")}</span>}</div></div></Link>}
export function CarGrid({cars}:{cars:Car[]}){return <div className="grid gap-5 grid-cols-1 sm:grid-cols-2 xl:grid-cols-4">{cars.map(car=><CarCard key={car.slug} car={car}/>)}</div>}
export function EmptyState({title,actionHref="/cars",action="Filtrlarni tozalash"}:{title:string;actionHref?:string;action?:string}){return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">{title}</h2><Link href={actionHref} className="mt-4 inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">{action}</Link></section>}
export function CatalogSkeleton(){return <div className="grid gap-5 grid-cols-1 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-80 animate-pulse rounded-2xl bg-slate-200"/>)}</div>}
