import Link from "next/link";
import { formatPrice, stockLabel, type FormatterLocale } from "@/lib/formatters";
type Car={slug:string;name:string;price:number;currency:string;year:number;stock_status:string;is_featured:boolean;body_type?:string|null;fuel_type?:string|null;transmission?:string|null;engine_volume?:number|string|null;brands?:{name:string;logo_url?:string|null}|null;car_images?:Array<{public_url:string|null;alt_text:string|null;is_primary:boolean;sort_order:number}>|null};
const labels={uz:{body:{sedan:"Sedan",suv:"SUV",hatchback:"Xetchbek",crossover:"Krossover",universal:"Universal",minivan:"Miniven",coupe:"Kupe",pickup:"Pikap"},fuel:{petrol:"Benzin",gasoline:"Benzin",benzin:"Benzin",diesel:"Dizel",electric:"Elektro",hybrid:"Gibrid"},transmission:{manual:"Mexanika",mechanic:"Mexanika",mexanika:"Mexanika",automatic:"Avtomat",avtomat:"Avtomat",cvt:"CVT"},image:"Rasm tez orada",brand:"Brend"},ru:{body:{sedan:"Седан",suv:"SUV",hatchback:"Хэтчбек",crossover:"Кроссовер",universal:"Универсал",minivan:"Минивэн",coupe:"Купе",pickup:"Пикап"},fuel:{petrol:"Бензин",gasoline:"Бензин",benzin:"Бензин",diesel:"Дизель",electric:"Электро",hybrid:"Гибрид"},transmission:{manual:"Механика",mechanic:"Механика",mexanika:"Механика",automatic:"Автомат",avtomat:"Автомат",cvt:"CVT"},image:"Фото скоро появится",brand:"Бренд"}} as const;
function imageFor(car:Car){return [...(car.car_images??[])].sort((a,b)=>Number(b.is_primary)-Number(a.is_primary)||a.sort_order-b.sort_order)[0]?.public_url}
function brandFallback(car:Car){return(car.brands?.name?.trim()||"?").slice(0,2).toUpperCase()}
function label(group:keyof typeof labels.uz,value:string|null|undefined,locale:FormatterLocale){if(!value)return null;const map=labels[locale][group] as Record<string,string>;return map[value.toLowerCase()]??value}
function engineLabel(value:number|string|null|undefined){if(value===null||value===undefined||value==="")return null;const numeric=Number(value);return Number.isFinite(numeric)?`${numeric%1===0?numeric.toFixed(0):numeric}L`:String(value)}
export function AvailabilityBadge({status,locale="uz"}:{status:string;locale?:FormatterLocale}){const tone=status==="available"?"bg-emerald-50 text-emerald-700":status==="coming_soon"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-700";return <span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone}`}>{stockLabel(status,locale)}</span>}
export function Price({amount,currency,locale="uz"}:{amount:number;currency:string;locale?:FormatterLocale}){return <p className="text-xl font-bold tracking-tight text-slate-950">{formatPrice(amount,currency,locale)}</p>}
export function CarCard({car,locale="uz"}:{car:Car;locale?:FormatterLocale}){const image=imageFor(car),brandName=car.brands?.name??"",specs=[label("transmission",car.transmission,locale),engineLabel(car.engine_volume),label("fuel",car.fuel_type,locale),label("body",car.body_type,locale)].filter(Boolean) as string[];return <Link href={`/cars/${car.slug}`} className="group block overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm transition duration-200 hover:-translate-y-0.5 hover:shadow-lg"><div className="relative aspect-[16/10] overflow-hidden bg-slate-100">{image?<img src={image} alt={car.car_images?.[0]?.alt_text??`${brandName} ${car.name}`} className="h-full w-full object-contain p-2" loading="lazy"/>:<div className="flex h-full items-center justify-center text-sm font-medium text-slate-500">{labels[locale].image}</div>}<div className="absolute left-3 top-3 flex h-11 w-11 items-center justify-center rounded-xl border border-slate-200 bg-white p-1.5 shadow-sm">{car.brands?.logo_url?<img src={car.brands.logo_url} alt={brandName} className="h-full w-full object-contain"/>:<span className="text-[10px] font-black uppercase text-slate-600">{brandFallback(car)}</span>}</div></div><div className="space-y-3 p-4"><div className="flex flex-wrap items-center gap-1.5 text-xs font-medium text-slate-500">{specs.map((spec,index)=><span key={`${spec}-${index}`}>{index>0&&<span className="mr-1.5 text-slate-300">•</span>}{spec}</span>)}</div><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{brandName}</p><h3 className="mt-1 text-lg font-black">{car.name}</h3></div><div className="flex flex-wrap items-end justify-between gap-3"><Price amount={car.price} currency={car.currency} locale={locale}/><div className="flex items-center gap-2"><AvailabilityBadge status={car.stock_status} locale={locale}/><span className="text-sm font-medium text-slate-500">{car.year}</span></div></div></div></Link>}
export function CarGrid({cars,locale="uz"}:{cars:Car[];locale?:FormatterLocale}){return <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">{cars.map(car=><CarCard key={car.slug} car={car} locale={locale}/>)}</div>}
export function EmptyState({title,actionHref="/cars",action="Filtrlarni tozalash"}:{title:string;actionHref?:string;action?:string}){return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">{title}</h2><Link href={actionHref} className="mt-4 inline-flex rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white">{action}</Link></section>}
export function CatalogSkeleton(){return <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:8},(_,i)=><div key={i} className="h-80 animate-pulse rounded-2xl bg-slate-200"/>)}</div>}
