"use client";
import {useState} from "react";
import {submitCreditApplicationAction} from "@/app/account/credit-actions";

type Props={orderId:string;financingProgramId:string;bankName:string;programName:string;locale:"uz"|"ru"};

const copy={
 uz:{title:"Kredit arizasini boshlash",intro:"Siz quyidagi kredit mahsulotini tanladingiz:",bank:"Bank",program:"Kredit dasturi",body:"Kredit arizasini ko‘rib chiqish uchun tanlangan bank kredit tarixi, MIB qarzdorligi, ish haqi va daromadlari hamda boshqa zarur ma’lumotlarni tekshirishi mumkin.",oneid:"Keyingi bosqichda OneID ilovasiga kirib, tanlagan bankingiz uchun ushbu ma’lumotlardan foydalanishga ruxsat berishingiz va tegishli qulfni ochishingiz kerak.",warning:"OneID ilovasida aynan tanlangan bank nomi va so‘ralayotgan ruxsatlarni tekshiring. Ruxsatni o‘zingiz berganingizga ishonch hosil qiling.",consent:"OneID ilovasida tanlagan bankim uchun kerakli ma’lumotlardan foydalanishga ruxsat berdim va qulfni ochdim.",continue:"Qulfni ochganimni tasdiqlayman, davom etish",cancel:"Bekor qilish",loading:"Yuborilmoqda...",success:"Kredit arizasi qabul qilindi. Menejer bankka yuborish uchun tekshiradi.",exists:"Ariza allaqachon mavjud."},
 ru:{title:"Начало кредитной заявки",intro:"Вы выбрали следующий кредитный продукт:",bank:"Банк",program:"Кредитная программа",body:"Для рассмотрения кредитной заявки выбранный банк может проверить кредитную историю, задолженность в МИБ, сведения о заработке и доходах, а также другие необходимые данные.",oneid:"На следующем этапе необходимо открыть приложение OneID, предоставить выбранному банку разрешение на использование этих данных и открыть соответствующий замок.",warning:"В приложении OneID проверьте название выбранного банка и запрашиваемые разрешения. Убедитесь, что разрешение предоставили именно вы.",consent:"Я предоставил выбранному банку разрешение на использование необходимых данных в приложении OneID и открыл замок.",continue:"Подтверждаю открытие замка, продолжить",cancel:"Отмена",loading:"Отправка...",success:"Кредитная заявка принята. Менеджер проверит её перед отправкой в банк.",exists:"Заявка уже существует."}
} as const;

export function CreditApplicationButton({orderId,financingProgramId,bankName,programName,locale}:Props){
 const[open,setOpen]=useState(false);const[consent,setConsent]=useState(false);const[loading,setLoading]=useState(false);const[message,setMessage]=useState("");const t=copy[locale];
 async function submit(){if(!consent)return;setLoading(true);setMessage("");const fd=new FormData();fd.set("orderId",orderId);fd.set("financingProgramId",financingProgramId);fd.set("oneidConsentConfirmed","true");const result=await submitCreditApplicationAction(fd);setLoading(false);if(result.status==="error"){setMessage(result.message);return}setMessage(result.status==="already_exists"?t.exists:t.success);if(result.status==="submitted")setOpen(false);}
 return <div className="mt-5 space-y-3"><button type="button" onClick={()=>{setOpen(true);setMessage("")}} className="w-full rounded-full bg-slate-950 py-3 font-bold text-white">{locale==="ru"?"Подать заявку на кредит":"Kreditga ariza berish"}</button>{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h3 className="text-xl font-black">{t.title}</h3><p className="mt-2 text-sm text-slate-600">{t.intro}</p><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><p><span className="text-slate-500">{t.bank}: </span><strong>{bankName}</strong></p><p className="mt-2"><span className="text-slate-500">{t.program}: </span><strong>{programName}</strong></p></div><p className="mt-4 text-sm text-slate-700">{t.body}</p><p className="mt-3 text-sm font-semibold text-slate-800">{t.oneid}</p><div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-slate-700">{t.warning}</div><label className="mt-4 flex cursor-pointer gap-3 text-sm font-semibold text-slate-800"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-4 w-4"/>{t.consent}</label><div className="mt-5 flex gap-3"><button type="button" onClick={()=>setOpen(false)} disabled={loading} className="flex-1 rounded-full border py-3 font-bold">{t.cancel}</button><button type="button" onClick={submit} disabled={!consent||loading} className="flex-1 rounded-full bg-slate-950 py-3 font-bold text-white disabled:opacity-40">{loading?t.loading:t.continue}</button></div>{message&&<p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm font-semibold text-slate-700">{message}</p>}</div></div>}{message&&!open&&<p className="rounded-lg bg-slate-50 p-3 text-sm font-semibold text-slate-700">{message}</p>}</div>
}
