"use client";
import { useMemo, useState } from "react";
import { formatPrice } from "@/lib/formatters";
import type { FinancingProgram } from "@/components/financing-options";

type Props={carPrice:number;currency:string;program:FinancingProgram;selected:boolean;selectable?:boolean;onSelect:()=>void};
type Row={month:number;payment:number;principal:number;interest:number;balance:number};
const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));
function monthlyPayment(p:number,r:number,m:number){if(p<=0||m<=0)return 0;const mr=r/100/12;if(mr===0)return Math.round(p/m);return Math.round((p*mr)/(1-Math.pow(1+mr,-m)));}
function buildSchedule(p:number,r:number,m:number):Row[]{if(p<=0||m<=0)return[];const mr=r/100/12;let balance=p;const payment=monthlyPayment(p,r,m);const rows:Row[]=[];for(let month=1;month<=m;month++){const interest=mr===0?0:Math.round(balance*mr);const principal=Math.min(balance,Math.max(0,payment-interest));const actual=principal+interest;balance=Math.max(0,balance-principal);rows.push({month,payment:actual,principal,interest,balance});}return rows;}
function termLabel(m:number){const y=Math.floor(m/12),r=m%12;if(!r)return `${y} yil (${m} oy)`;return `${y} yil ${r} oy (${m} oy)`;}
export function FinancingCalculator({carPrice,currency,program,selected,selectable=true,onSelect}:Props){
 const minDown=clamp(Number(program.min_down_payment_percent??0),0,100);
 // max_financing_percent caps the financed portion; customers may pay more upfront, so the UI remains draggable up to 100%.
 const maxDown=100;
 const minTerm=Math.max(1,Math.round(Number(program.min_term_months??12)));
 const maxTerm=Math.max(minTerm,Math.round(Number(program.max_term_months??minTerm)));
 const[down,setDown]=useState(minDown);const[term,setTerm]=useState(maxTerm);const[details,setDetails]=useState(false);
 const calc=useMemo(()=>{const downAmount=Math.round(carPrice*down/100);const principal=Math.max(0,carPrice-downAmount);const rate=Number(program.annual_interest_rate??0);const payment=monthlyPayment(principal,rate,term);const schedule=buildSchedule(principal,rate,term);const total=schedule.reduce((s,r)=>s+r.payment,0);const interest=schedule.reduce((s,r)=>s+r.interest,0);const insurance=program.insurance_amount!=null?Number(program.insurance_amount):program.insurance_percent!=null?Math.round(carPrice*Number(program.insurance_percent)/100):0;return{downAmount,principal,rate,payment,schedule,total,interest,insurance};},[carPrice,down,program.annual_interest_rate,program.insurance_amount,program.insurance_percent,term]);
 return <article className={`rounded-3xl border-2 bg-white p-4 shadow-sm transition ${selected?"border-slate-950 shadow-md":"border-slate-200"}`}>
  <button type="button" onClick={onSelect} disabled={!selectable} className="w-full cursor-pointer text-left disabled:cursor-default"><div className="flex items-start gap-3"><div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-2xl border bg-slate-50">{program.banks?.logo_url?<img src={program.banks.logo_url} alt={program.banks.name} className="h-full w-full object-contain p-2"/>:<span className="text-xs font-black text-slate-500">{program.banks?.name?program.banks.name.slice(0,2).toUpperCase():"DILER"}</span>}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><p className="text-base font-black text-slate-950">{program.banks?.name??"Diler hisobidan"}</p><p className="text-sm font-semibold text-slate-600">{program.name}</p></div><span aria-hidden="true" className={`mt-1 inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 ${selected?"border-slate-950 bg-slate-950 text-white":"border-slate-300"}`}>{selected?"✓":""}</span></div></div></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Foiz</p><p className="mt-1 font-black">{calc.rate}%</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Boshlang&apos;ich</p><p className="mt-1 font-black">{down.toFixed(2).replace(/\.00$/,"")}%</p></div><div className="rounded-2xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Muddat</p><p className="mt-1 font-black">{termLabel(term)}</p></div></div></button>
  <div className="mt-4 rounded-2xl bg-slate-950 p-4 text-white"><p className="text-xs text-slate-300">Hisoblangan oylik to&apos;lov</p><p className="mt-1 text-2xl font-black">{formatPrice(calc.payment,program.currency??currency)} / oy</p><p className="mt-1 text-xs text-slate-300">Moliyalashtirish: {formatPrice(calc.principal,program.currency??currency)}</p></div>
  <div className="mt-4 space-y-4"><label className="block"><div className="flex items-center justify-between gap-3 text-sm font-bold"><span>Boshlang&apos;ich to&apos;lov</span><span>{down.toFixed(2).replace(/\.00$/,"")}% · {formatPrice(calc.downAmount,program.currency??currency)}</span></div><input aria-label="Boshlang'ich to'lov" type="range" min={minDown} max={maxDown} step="0.1" value={down} onChange={e=>setDown(Number(e.target.value))} onInput={e=>setDown(Number(e.currentTarget.value))} className="mt-2 block h-2 w-full cursor-pointer touch-none accent-slate-950"/><div className="mt-1 flex justify-between text-xs text-slate-500"><span>{minDown}%</span><span>100%</span></div></label><label className="block"><div className="flex items-center justify-between gap-3 text-sm font-bold"><span>Muddat</span><span>{termLabel(term)}</span></div><input aria-label="Kredit muddati" type="range" min={minTerm} max={maxTerm} step="1" value={term} onChange={e=>setTerm(Number(e.target.value))} onInput={e=>setTerm(Number(e.currentTarget.value))} className="mt-2 block h-2 w-full cursor-pointer touch-none accent-slate-950"/><div className="mt-1 flex justify-between text-xs text-slate-500"><span>{termLabel(minTerm)}</span><span>{termLabel(maxTerm)}</span></div></label></div>
  {(calc.insurance>0||program.insurance_type||program.benefits_uz)&&<div className="mt-4 rounded-2xl border bg-amber-50 p-4"><p className="font-black">Qo&apos;shimcha shartlar</p>{program.insurance_type&&<p className="mt-2 text-sm"><b>Sug&apos;urta:</b> {program.insurance_type}{calc.insurance>0?` — ${formatPrice(calc.insurance,program.currency??currency)}`:""}</p>}{program.benefits_uz&&<p className="mt-2 whitespace-pre-line text-sm"><b>Imtiyozlar:</b> {program.benefits_uz}</p>}</div>}
  <button type="button" onClick={()=>setDetails(v=>!v)} className="mt-4 w-full rounded-2xl border border-slate-300 px-4 py-3 text-sm font-black">{details?"Batafsil hisob-kitobni yopish":"Batafsil hisob-kitob · oyma-oy jadval"}</button>
  {details&&<div className="mt-4 overflow-hidden rounded-2xl border border-slate-200"><div className="grid gap-2 bg-slate-50 p-3 text-sm sm:grid-cols-3"><div><span className="text-slate-500">Boshlang&apos;ich:</span> <b>{formatPrice(calc.downAmount,program.currency??currency)}</b></div><div><span className="text-slate-500">Jami kredit to&apos;lovi:</span> <b>{formatPrice(calc.total+calc.downAmount,program.currency??currency)}</b></div><div><span className="text-slate-500">Jami foiz:</span> <b>{formatPrice(calc.interest,program.currency??currency)}</b></div></div><div className="max-h-80 overflow-auto"><table className="w-full min-w-[620px] text-sm"><thead className="sticky top-0 bg-white text-left text-xs uppercase text-slate-500 shadow-sm"><tr><th className="p-3">Oy</th><th className="p-3">To&apos;lov</th><th className="p-3">Asosiy qarz</th><th className="p-3">Foiz</th><th className="p-3">Qoldiq</th></tr></thead><tbody>{calc.schedule.map(row=><tr key={row.month} className="border-t border-slate-100"><td className="p-3 font-semibold">{row.month}</td><td className="p-3">{formatPrice(row.payment,program.currency??currency)}</td><td className="p-3">{formatPrice(row.principal,program.currency??currency)}</td><td className="p-3">{formatPrice(row.interest,program.currency??currency)}</td><td className="p-3 font-semibold">{formatPrice(row.balance,program.currency??currency)}</td></tr>)}</tbody></table></div></div>}
  {program.description&&<p className="mt-3 text-xs leading-5 text-slate-500">{program.description}</p>}{program.eligibility_notes&&<p className="mt-2 text-xs leading-5 text-slate-500">{program.eligibility_notes}</p>}{program.source_url&&<a href={program.source_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-block text-xs font-bold underline">Rasmiy manba</a>}
 </article>;
}
