"use client";
import { FinancingCalculator } from "@/components/financing-calculator";
import type { FormatterLocale } from "@/lib/formatters";
type Bank = { id:string; name:string; name_ru?:string|null; code:string; logo_url:string|null; website_url:string|null; integration_status:string; display_order:number };
export type FinancingRule = { id:string; down_payment_percent:number; term_months:number; annual_interest_rate:number; is_available:boolean; display_order:number };
export type FinancingProgram = { id:string; name:string; name_uz?:string|null; name_ru?:string|null; description:string|null; description_ru?:string|null; financing_type:string; annual_interest_rate:number|null; min_down_payment_percent:number|null; max_financing_percent:number|null; min_term_months:number|null; max_term_months:number|null; min_amount:number|null; max_amount:number|null; currency:string; eligibility_notes:string|null; eligibility_notes_ru?:string|null; source_url:string|null; source_label:string|null; last_verified_at:string|null; insurance_type:string|null; insurance_type_ru?:string|null; insurance_amount:number|null; insurance_percent:number|null; benefits_uz:string|null; benefits_ru:string|null; banks:Bank|null; financing_program_rules?: FinancingRule[] };
const LABEL={uz:{credit:"Kredit",installment:"Bo‘lib to‘lash",promotional:"Aksiya",title:"Kredit va bo‘lib to‘lash variantlari",hint:"Tanlangan avtomobil uchun faqat bank yoki diler belgilagan boshlang‘ich to‘lov va muddat kombinatsiyalari ko‘rsatiladi.",unavailableInstallment:"Bu avtomobilni bo‘lib to‘lashga sotib olib bo‘lmaydi",unavailableCredit:"Kredit shartlari hozircha mavjud emas."},ru:{credit:"Кредит",installment:"Рассрочка",promotional:"Акция",title:"Варианты кредита и рассрочки",hint:"Для выбранного автомобиля отображаются только комбинации первоначального взноса и срока, установленные банком или дилером.",unavailableInstallment:"Этот автомобиль нельзя приобрести в рассрочку",unavailableCredit:"Условия кредита пока недоступны."}} as const;
function isZeroPercentProgram(program:FinancingProgram){const rules=Array.isArray(program.financing_program_rules)?program.financing_program_rules.filter(r=>r.is_available!==false):[];if(rules.length)return rules.every(r=>Number(r.annual_interest_rate)===0);return Number(program.annual_interest_rate??0)===0;}
export function FinancingOptions({carPrice,currency,programs,selectedProgramId=null,onSelectProgram,purchaseType="credit",locale="uz"}:{carPrice:number;currency:string;programs:FinancingProgram[];selectedProgramId?:string|null;onSelectProgram?:(id:string)=>void;purchaseType:"credit"|"installment";locale?:FormatterLocale}){const l=LABEL[locale];const visiblePrograms=programs.filter(program=>purchaseType==="installment"?(program.financing_type==="installment"||(program.financing_type==="credit"&&isZeroPercentProgram(program))):program.financing_type==="credit");if(!visiblePrograms.length)return <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center text-sm font-semibold text-slate-600">{purchaseType==="installment"?l.unavailableInstallment:l.unavailableCredit}</div>;return <div className="space-y-4"><div><p className="text-lg font-black">{l.title}</p><p className="mt-1 text-sm text-slate-500">{l.hint}</p></div>{visiblePrograms.map(program=>{const bankName=program.banks?(locale==="ru"?program.banks.name_ru??program.banks.name:program.banks.name):(locale==="ru"?"Дилер":"Diler hisobidan");const programName=locale==="ru"?program.name_ru??program.name:program.name_uz??program.name;const localizedProgram={...program,name:programName,insurance_type:locale==="ru"?program.insurance_type_ru??program.insurance_type:program.insurance_type,description:locale==="ru"?program.description_ru??program.description:program.description,eligibility_notes:locale==="ru"?program.eligibility_notes_ru??program.eligibility_notes:program.eligibility_notes,banks:program.banks?{...program.banks,name:bankName}:program.banks};return <div key={program.id}><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-slate-500"><span>{l[program.financing_type as keyof typeof l]??program.financing_type}</span></div><FinancingCalculator carPrice={carPrice} currency={currency} program={localizedProgram} selected={selectedProgramId===program.id} selectable={true} onSelect={()=>onSelectProgram?.(program.id)} locale={locale}/></div>})}</div>;}
