import { CarCard } from "@/components/catalog-ui";
import { FinancingService } from "@/services/financing-service";
import { formatPrice } from "@/lib/formatters";

type Car = { id:string; slug:string; name:string; price:number; currency:string; year:number; stock_status:string; is_featured:boolean; body_type?:string|null; fuel_type?:string|null; transmission?:string|null; engine_volume?:number|string|null; brands?:{name:string;logo_url?:string|null}|null; car_images?:Array<{public_url:string|null;alt_text:string|null;is_primary:boolean;sort_order:number}>|null };

function best(programs:any[], type:string){const xs=programs.filter(p=>p.financing_type===type);if(!xs.length)return null;return [...xs].sort((a,b)=>Number(a.annual_interest_rate??0)-Number(b.annual_interest_rate??0)||Number(b.max_term_months??0)-Number(a.max_term_months??0))[0];}
function payment(price:number,p:any){const down=Math.round(price*Number(p.min_down_payment_percent??0)/100);const principal=Math.max(0,price-down);const n=Math.max(1,Number(p.max_term_months??p.min_term_months??12));const r=Number(p.annual_interest_rate??0)/100/12;return r===0?Math.round(principal/n):Math.round(principal*r/(1-Math.pow(1+r,-n)));}

export async function HomeFinancingGrid({cars}:{cars:Car[]}){const service=new FinancingService();const unique=[...new Map(cars.map(c=>[c.id,c])).values()];const pairs=await Promise.all(unique.map(async car=>[car.id,(await service.getApplicableProgramsForCar(car.id)).data??[]] as const));const map=new Map(pairs);return <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4">{cars.map(car=>{const programs=map.get(car.id)??[];const credit=best(programs,"credit");const installment=best(programs,"installment");return <div key={car.id} className="min-w-0"><CarCard car={car}/>{(credit||installment)?<div className="-mt-2 space-y-2 rounded-b-2xl border border-t-0 border-slate-200 bg-white px-4 pb-4 pt-3">{credit?<div className="rounded-xl bg-emerald-50 p-3"><p className="text-xs font-bold text-emerald-700">Kredit {Number(credit.annual_interest_rate??0)}%</p><p className="text-xs text-slate-600">Avans {Number(credit.min_down_payment_percent??0)}% · {credit.max_term_months??credit.min_term_months} oy</p><p className="font-black">{formatPrice(payment(car.price,credit),car.currency)} / oy</p></div>:null}{installment?<div className="rounded-xl bg-amber-50 p-3"><p className="text-xs font-bold text-amber-700">Bo‘lib to‘lash</p><p className="text-xs text-slate-600">Avans {Number(installment.min_down_payment_percent??0)}% · {installment.max_term_months??installment.min_term_months} oy</p><p className="font-black">{formatPrice(payment(car.price,installment),car.currency)} / oy</p></div>:null}</div>:null}</div>})}</div>}
