import Image from "next/image";
import Link from "next/link";
import { LanguageSwitcher } from "@/components/language-switcher";
import { getLocale } from "@/lib/locale";
import { t } from "@/lib/i18n";
import { getCurrentCustomer } from "@/lib/customer-session";
import { signOutCustomerAction } from "@/app/account/sign-out-action";

export async function Header(){const locale=await getLocale();const x=t(locale);const customer=await getCurrentCustomer();return <header className="overflow-x-hidden border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-3 sm:px-5 sm:py-4"><div className="flex min-w-0 items-center justify-between gap-3 sm:gap-5"><Link href="/" className="flex min-w-0 shrink-0 items-center leading-none" aria-label="Cardrive.uz"><Image src="/cardrive-header-original.svg" alt="Cardrive.uz" width={210} height={60} priority sizes="(max-width: 639px) 150px, 210px" className="block h-auto w-[150px] sm:w-[210px]" /></Link><form action="/cars" method="get" className="hidden min-w-0 flex-1 md:block md:max-w-xl"><div className="relative"><input name="q" aria-label={x.searchCar} placeholder={x.searchCar+"..."} className="h-10 w-full rounded-full border border-slate-200 bg-slate-50 pl-4 pr-14 text-sm outline-none transition focus:border-slate-400 focus:bg-white"/><button type="submit" aria-label={x.find} className="absolute right-1 top-1 flex h-8 w-8 items-center justify-center rounded-full bg-slate-950 text-white"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5" strokeLinecap="round"/></svg></button></div></form><div className="flex min-w-0 max-w-[calc(100vw-180px)] flex-wrap items-center justify-end gap-2 sm:max-w-none sm:flex-nowrap sm:gap-4"><LanguageSwitcher/><nav aria-label={x.navLabel} className="flex w-full min-w-0 items-center justify-end gap-1 text-sm font-medium text-slate-700 sm:w-auto sm:gap-4">{customer?(<><Link className="whitespace-nowrap rounded-full border border-slate-300 px-2 py-1.5 text-xs font-semibold sm:px-4 sm:py-2 sm:text-sm" href="/account/orders">{x.orders}</Link><form action={signOutCustomerAction}><button className="whitespace-nowrap rounded-full border border-slate-300 px-2 py-1.5 text-xs font-semibold sm:px-4 sm:py-2 sm:text-sm">{x.logout}</button></form></>):<Link href="/account/login" className="whitespace-nowrap rounded-full border border-slate-300 px-2 py-1.5 text-xs font-semibold sm:px-4 sm:py-2 sm:text-sm">{x.login}</Link>}</nav></div></div><form action="/cars" method="get" className="mt-3 md:hidden"><div className="relative"><input name="q" aria-label={x.searchCar} placeholder={x.searchCar+"..."} className="h-10 w-full rounded-full border border-slate-200 bg-slate-50 pl-4 pr-14 text-sm outline-none focus:border-slate-400 focus:bg-white"/><button type="submit" aria-label={x.find} className="absolute right-1 top-1 flex h-8 w-8 items-center justify-center rounded-full bg-slate-950 text-white"><svg aria-hidden="true" viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 5 5" strokeLinecap="round"/></svg></button></div></form></div></header>}

export async function Footer(){const locale=await getLocale();const x=t(locale);return <footer className="mt-16 border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-10 text-sm text-slate-600 sm:grid-cols-2 lg:grid-cols-4"><div><Link href="/" aria-label="Cardrive.uz" className="inline-flex w-fit"><Image src="/cardrive-footer.webp" alt="Cardrive.uz — drive your way" width={240} height={189} className="h-auto w-[180px] sm:w-[200px] object-contain" /></Link><p className="mt-3 max-w-xs leading-6">{x.footerDescription}</p></div><div><p className="font-bold text-slate-950">{x.cars}</p><div className="mt-3 space-y-2"><Link className="block hover:underline" href="/cars">{x.allCars}</Link><Link className="block hover:underline" href="/cars?category=popular">{x.popular}</Link><Link className="block hover:underline" href="/cars?category=installment">{x.installment}</Link><Link className="block hover:underline" href="/cars?category=discounts">{x.discounts}</Link><Link className="block hover:underline" href="/cars?category=electric">{x.electric}</Link><Link className="block hover:underline" href="/cars?category=hybrid">{x.hybrid}</Link><Link className="block hover:underline" href="/cars?category=premium">{x.premium}</Link><Link className="block hover:underline" href="/cars?category=commercial">{x.commercial}</Link></div></div><div><p className="font-bold text-slate-950">{x.footerForBuyers}</p><div className="mt-3 space-y-2"><Link className="block hover:underline" href="/avtokredit">{x.footerCredit}</Link><Link className="block hover:underline" href="/account/orders">{x.orders}</Link><Link className="block hover:underline" href="/faq">{x.footerFaq}</Link><Link className="block hover:underline" href="/privacy">{x.footerPrivacy}</Link><Link className="block hover:underline" href="/terms">{x.footerTerms}</Link></div></div><div><p className="font-bold text-slate-950">{x.footerContact}</p><div className="mt-3 space-y-2"><a className="block hover:underline" href="tel:+998998244494">+998 99 824 44 94</a><a className="block hover:underline" href="https://t.me/CarDriveUzBot" target="_blank" rel="noreferrer">@CarDriveUzBot</a></div></div></div><div className="border-t border-slate-200"><div className="mx-auto flex max-w-7xl flex-col gap-2 px-4 py-4 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><span>{x.footerCopyright}</span><span>{x.footerLegalNote}</span></div></div></footer>}
