import Image from "next/image";
import Link from "next/link";
import { LanguageSwitcher } from "@/components/language-switcher";
import { getLocale, t } from "@/lib/i18n";
import { getCurrentCustomer } from "@/lib/customer-session";
import { signOutCustomerAction } from "@/app/account/sign-out-action";

const categories=[{key:"popular",uz:"Mashhur",ru:"Популярные авто",icon:"🔥"},{key:"installment",uz:"Foizsiz",ru:"Беспроцентная рассрочка",icon:"💳"},{key:"discounts",uz:"Chegirmalar",ru:"Горячие скидки",icon:"🔥"},{key:"electric",uz:"Elektr",ru:"Электрические",icon:"⚡"},{key:"hybrid",uz:"Gibrid",ru:"Гибридные",icon:"🔋"},{key:"premium",uz:"Premium",ru:"Премиальные",icon:"💎"},{key:"commercial",uz:"Tijorat",ru:"Коммерческие",icon:"🚐"}];

export async function Header(){const locale=await getLocale();const x=t(locale);const customer=await getCurrentCustomer();return <header className="overflow-x-hidden border-b border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-4 sm:px-5"><div className="flex min-w-0 items-center justify-between gap-3 sm:gap-5"><Link href="/" className="flex shrink-0 items-center" aria-label="Cardrive.uz"><Image src="/cardrive-header-original.svg" alt="Cardrive.uz" width={140} height={40} priority className="h-10 w-auto object-contain" /></Link><form action="/cars" method="get" className="hidden min-w-0 flex-1 md:block md:max-w-xl"><div className="relative"><input name="q" aria-label={locale==="ru"?"Поиск автомобиля":"Avtomobil qidirish"} placeholder={locale==="ru"?"Поиск автомобиля...":"Avtomobil qidirish..."} className="h-10 w-full rounded-full border border-slate-200 bg-slate-50 pl-4 pr-12 text-sm outline-none transition focus:border-slate-400 focus:bg-white"/><button type="submit" aria-label={locale==="ru"?"Найти":"Qidirish"} className="absolute right-1 top-1 flex h-8 w-8 items-center justify-center rounded-full bg-slate-950 text-sm text-white">⌕</button></div></form><div className="flex min-w-0 shrink-0 items-center gap-2 sm:gap-4"><LanguageSwitcher/><nav aria-label="Asosiy navigatsiya" className="flex min-w-0 items-center gap-2 text-sm font-medium text-slate-700 sm:gap-4">{customer?(<><Link className="whitespace-nowrap rounded-full border border-slate-300 px-4 py-2 font-semibold" href="/account/orders">Buyurtmalarim</Link><form action={signOutCustomerAction}><button className="whitespace-nowrap rounded-full border border-slate-300 px-4 py-2 font-semibold">Chiqish</button></form></>):<Link href="/account/login" className="whitespace-nowrap rounded-full border border-slate-300 px-4 py-2 font-semibold">Kirish</Link>}</nav></div></div><form action="/cars" method="get" className="mt-3 md:hidden"><div className="relative"><input name="q" aria-label={locale==="ru"?"Поиск автомобиля":"Avtomobil qidirish"} placeholder={locale==="ru"?"Поиск автомобиля...":"Avtomobil qidirish..."} className="h-10 w-full rounded-full border border-slate-200 bg-slate-50 pl-4 pr-12 text-sm outline-none focus:border-slate-400 focus:bg-white"/><button type="submit" aria-label={locale==="ru"?"Найти":"Qidirish"} className="absolute right-1 top-1 flex h-8 w-8 items-center justify-center rounded-full bg-slate-950 text-sm text-white">⌕</button></div></form><nav aria-label={x.categories} className="mt-4 flex gap-2 overflow-x-auto pb-1">{categories.map(category=><Link key={category.key} href={`/cars?category=${category.key}`} className="whitespace-nowrap rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-700 hover:border-slate-300"><span className="mr-1">{category.icon}</span>{locale==="ru"?category.ru:category.uz}</Link>)}</nav></div></header>}

export async function Footer(){const locale=await getLocale();const x=t(locale);return <footer className="mt-16 border-t border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl gap-6 px-4 py-10 text-sm text-slate-600 sm:grid-cols-3"><div><Link href="/" aria-label="Cardrive.uz" className="inline-block"><Image src="/cardrive-logo.svg" alt="Cardrive.uz — drive your way" width={220} height={125} className="h-auto w-[220px]" /></Link><p className="mt-2">{x.trusted}</p></div><div><p className="font-bold text-slate-950">{x.cars}</p><Link className="mt-2 block hover:underline" href="/cars">{x.allCars}</Link></div><div><p className="font-bold text-slate-950">{x.info}</p><p className="mt-2">{x.contactSoon}</p></div></div></footer>}
