import { cookies } from "next/headers";
export type Locale = "uz" | "ru";
export const DEFAULT_LOCALE: Locale = "uz";
export const translations = {
  uz: { cars:"Avtomobillar", catalog:"Katalogni ko‘rish", search:"Qidirish", searchPlaceholder:"Brend yoki modelni qidiring...", categories:"Kategoriyalar", all:"Barchasi", featured:"Tavsiya etilgan avtomobillar", available:"Mavjud avtomobillar", brands:"Brendlar", brandHint:"Brendni tanlang va uning modellari bilan tanishing.", modelCount:"model", newCars:"Yangi avtomobillar", findCar:"Sizga mos avtomobilni toping.", filters:"Qidiruv va filtrlar", found:"ta avtomobil topildi", noSearch:"Qidiruv bo‘yicha avtomobil topilmadi", noMatch:"Mos avtomobillar topilmadi", back:"Katalogga qaytish", unavailable:"Hozircha mavjud emas", advice:"Maslahat olish", description:"Tavsif", specs:"Texnik xususiyatlar", body:"Kuzov", fuel:"Yoqilg‘i", transmission:"Transmissiya", drive:"Yuritma", engine:"Dvigatel", power:"Quvvat", range:"Masofa", seats:"O‘rindiqlar", color:"Rang", newMarketplace:"Yangi avtomobillar marketplace’i", choose:"Yangi avtomobilingizni ishonch bilan tanlang.", chooseHint:"Brend, model, narx va texnik xususiyatlar bo‘yicha qidiring.", allCars:"Barcha avtomobillar", info:"Ma’lumot", contactSoon:"Aloqa va huquqiy ma’lumotlar tez orada.", trusted:"Yangi avtomobillar uchun ishonchli marketplace.", popular:"Mashhur", installment:"Foizsiz", discounts:"Chegirmalar", electric:"Elektr", hybrid:"Gibrid", premium:"Premium", commercial:"Tijorat", heroEyebrow:"YANGI VA ISHONCHLI", heroTitle:"O‘zbekistonda yangi avtomobillar katalogi", heroDescription:"Chevrolet, BYD, Kia va boshqa yangi avtomobillarni narxi, komplektatsiyasi va texnik xususiyatlari bilan tanlang.", login:"Kirish", logout:"Chiqish", orders:"Buyurtmalarim", navLabel:"Asosiy navigatsiya", searchCar:"Avtomobil qidirish", find:"Qidirish" },
  ru: { cars:"Автомобили", catalog:"Смотреть каталог", search:"Поиск", searchPlaceholder:"Поиск по бренду или модели...", categories:"Категории", all:"Все", featured:"Рекомендуемые автомобили", available:"Автомобили в наличии", brands:"Бренды", brandHint:"Выберите бренд и ознакомьтесь с его моделями.", modelCount:"моделей", newCars:"Новые автомобили", findCar:"Найдите подходящий вам автомобиль.", filters:"Поиск и фильтры", found:"автомобилей найдено", noSearch:"Автомобиль по вашему запросу не найден", noMatch:"Подходящие автомобили не найдены", back:"Вернуться в каталог", unavailable:"Пока недоступен", advice:"Получить консультацию", description:"Описание", specs:"Технические характеристики", body:"Кузов", fuel:"Топливо", transmission:"Трансмиссия", drive:"Привод", engine:"Двигатель", power:"Мощность", range:"Запас хода", seats:"Мест", color:"Цвет", newMarketplace:"Маркетплейс новых автомобилей", choose:"Выберите новый автомобиль с уверенностью.", chooseHint:"Ищите по бренду, модели, цене и техническим характеристикам.", allCars:"Все автомобили", info:"Информация", contactSoon:"Контактная и юридическая информация скоро появится.", trusted:"Надёжный маркетплейс новых автомобилей.", popular:"Популярные", installment:"Рассрочка 0%", discounts:"Горячие скидки", electric:"Электрические", hybrid:"Гибридные", premium:"Премиальные", commercial:"Коммерческие", heroEyebrow:"НОВЫЕ И НАДЁЖНЫЕ", heroTitle:"Каталог новых автомобилей в Узбекистане", heroDescription:"Выбирайте новые автомобили Chevrolet, BYD, Kia и других брендов, сравнивая цены, комплектации и технические характеристики.", login:"Войти", logout:"Выйти", orders:"Мои заказы", navLabel:"Основная навигация", searchCar:"Поиск автомобиля", find:"Найти" }
} as const;
export function t(locale: Locale) { return translations[locale]; }
export async function getLocale(): Promise<Locale> { const value = (await cookies()).get("cardrive-locale")?.value; return value === "ru" ? "ru" : "uz"; }
