import Link from "next/link";
import { AdminReconciliationRepository, type ReconciliationFilters } from "@/repositories/admin-reconciliation-repository";

const money=(n:number)=>new Intl.NumberFormat("uz-UZ").format(Math.round(n))+" UZS";
const dt=(v:string)=>v?new Intl.DateTimeFormat("uz-UZ",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Tashkent"}).format(new Date(v)):"—";
const q=(p:Record<string,string|undefined>)=>new URLSearchParams(Object.entries(p).filter(([,v])=>v).map(([k,v])=>[k,v!]));

export default async function ReconciliationPage({searchParams}:{searchParams:Promise<ReconciliationFilters>}){
  const p=await searchParams; const repo=new AdminReconciliationRepository(); const rows=await repo.list(p); const qs=q(p as Record<string,string|undefined>);
  const csv=`/admin/reconciliation/export?${qs.toString()}`;
  const totals={sales:rows.length,amount:rows.reduce((s,r)=>s+r.price,0),down:rows.reduce((s,r)=>s+r.downPayment,0),financed:rows.reduce((s,r)=>s+r.financedAmount,0)};
  return <main className="mx-auto max-w-[1600px] px-6 py-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin" className="text-sm font-bold underline">← Analitika</Link><h1 className="mt-3 text-3xl font-black">Bank / diler sverka reyestri</h1><p className="mt-1 text-sm text-slate-500">Tanlangan davr va filtr bo‘yicha batafsil operatsion ma’lumotlar.</p></div><a href={csv} className="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Excelga eksport</a></div>
  <form method="get" className="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-7"><label className="grid gap-1 text-xs font-bold text-slate-500">Sana: dan<input name="dateFrom" type="date" defaultValue={p.dateFrom} className="rounded-lg border p-2 text-sm text-slate-900"/></label><label className="grid gap-1 text-xs font-bold text-slate-500">Sana: gacha<input name="dateTo" type="date" defaultValue={p.dateTo} className="rounded-lg border p-2 text-sm text-slate-900"/></label><Select name="bank" value={p.bank} label="Bank" options={[...new Set(rows.map(x=>x.bank).filter(x=>x!=="—"))]}/><Select name="dealer" value={p.dealer} label="Diler" options={[...new Set(rows.map(x=>x.dealer).filter(x=>x!=="—"))]}/><Select name="program" value={p.program} label="Kredit dasturi" options={[...new Set(rows.map(x=>x.program).filter(x=>x!=="—"))]}/><Select name="purchaseType" value={p.purchaseType} label="Sotuv turi" options={["credit","installment","cash","online"]}/><Select name="status" value={p.status} label="Holat" options={["pending","confirmed","processing","completed","cancelled"]}/><div className="flex items-end gap-2 lg:col-span-7"><button className="rounded-lg bg-slate-950 px-4 py-2 text-sm font-bold text-white">Filtrlash</button><Link href="/admin/reconciliation" className="rounded-lg border px-4 py-2 text-sm font-semibold">Tozalash</Link></div></form>
  <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Reyestrdagi yozuvlar" value={String(totals.sales)}/><Metric label="Avtomobil summasi" value={money(totals.amount)}/><Metric label="Boshlang‘ich to‘lov" value={money(totals.down)}/><Metric label="Moliyalashtirish" value={money(totals.financed)}/></div>
  <div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-[1700px] w-full text-sm"><thead className="bg-slate-50"><tr>{["Ariza / buyurtma","Sana","Mijoz","Telefon","Avtomobil","Rang","Narx","Boshlang‘ich to‘lov","Kredit summasi","Foiz","Muddat","Bank","Dastur","Diler","Turi","Holat","Ariza","OneID","Bankka yuborilgan"].map(x=><th key={x} className="whitespace-nowrap px-3 py-3 text-left font-bold">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-3"><Link className="font-bold underline" href={`/admin/orders/${r.id}`}>{r.orderNumber}</Link></td><td className="px-3 py-3 whitespace-nowrap">{dt(r.createdAt)}</td><td className="px-3 py-3">{r.customerName}</td><td className="px-3 py-3">{r.phone}</td><td className="px-3 py-3 font-semibold">{r.car}</td><td className="px-3 py-3">{r.color}</td><td className="px-3 py-3 whitespace-nowrap">{money(r.price)}</td><td className="px-3 py-3 whitespace-nowrap">{money(r.downPayment)}</td><td className="px-3 py-3 whitespace-nowrap">{money(r.financedAmount)}</td><td className="px-3 py-3">{r.interestRate}%</td><td className="px-3 py-3">{r.termMonths} oy</td><td className="px-3 py-3">{r.bank}</td><td className="px-3 py-3">{r.program}</td><td className="px-3 py-3">{r.dealer}</td><td className="px-3 py-3">{r.purchaseType}</td><td className="px-3 py-3">{r.status}</td><td className="px-3 py-3 whitespace-nowrap">{dt(r.applicationCreatedAt)}</td><td className="px-3 py-3 whitespace-nowrap">{dt(r.consentAt)}</td><td className="px-3 py-3 whitespace-nowrap">{dt(r.submittedAt)}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-slate-500">Tanlangan filtr bo‘yicha ma’lumot topilmadi.</p>}</div></main>;
}
function Select({name,value,label,options}:{name:string;value?:string;label:string;options:string[]}){return <label className="grid gap-1 text-xs font-bold text-slate-500">{label}<select name={name} defaultValue={value??""} className="rounded-lg border p-2 text-sm text-slate-900"><option value="">Barcha {label.toLowerCase()}lar</option>{options.map(x=><option key={x} value={x}>{x}</option>)}</select></label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
