import { AdminTable, Field } from "@/components/admin-ui";
import { createServiceRoleClient } from "@/supabase/server";
import { createCategoryAction, toggleCategoryAction } from "@/app/admin/marketplace-actions";

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const p = await searchParams;
  const result = await createServiceRoleClient().from("car_categories").select("*").order("sort_order").order("name_uz");
  return <div><h1 className="text-3xl font-black">Kategoriyalar</h1>{p.error ? <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{p.error}</div> : null}<div className="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]"><section>{result.data?.length ? <AdminTable><thead className="border-b bg-slate-50"><tr><th className="p-3">Kategoriya</th><th className="p-3">RU</th><th className="p-3">Tartib</th><th className="p-3">Holat</th></tr></thead><tbody>{result.data.map((category) => <tr key={category.id} className="border-b last:border-0"><td className="p-3 font-semibold">{category.icon ? `${category.icon} ` : ""}{category.name_uz}<div className="text-xs text-slate-500">{category.key}</div></td><td className="p-3">{category.name_ru}</td><td className="p-3">{category.sort_order}</td><td className="p-3"><form action={toggleCategoryAction}><input type="hidden" name="id" value={category.id}/><input type="hidden" name="isActive" value={category.is_active ? "" : "on"}/><button className="font-bold">{category.is_active ? "Faol" : "Nofaol"}</button></form></td></tr>)}</tbody></AdminTable> : <p className="rounded-xl border border-dashed p-8 text-center text-slate-500">Kategoriyalar mavjud emas.</p>}</section><form action={createCategoryAction} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Yangi kategoriya</h2><Field name="key" label="Kalit" required/><Field name="nameUz" label="O‘zbekcha nom" required/><Field name="nameRu" label="Ruscha nom" required/><Field name="icon" label="Icon"/><Field name="sortOrder" label="Tartib" type="number" defaultValue={0}/><label className="flex gap-2 text-sm font-semibold"><input type="checkbox" name="isActive" defaultChecked/>Faol</label><button className="w-full rounded-full bg-slate-950 py-3 font-bold text-white">Saqlash</button></form></div></div>;
}
