alter table public.banks add column if not exists name_uz text;
alter table public.dealers add column if not exists name_uz text;
alter table public.dealers add column if not exists name_ru text;
alter table public.dealers add column if not exists region_uz text;
alter table public.dealers add column if not exists region_ru text;
alter table public.dealers add column if not exists description_uz text;
alter table public.dealers add column if not exists description_ru text;
alter table public.financing_programs add column if not exists name_uz text;
alter table public.financing_programs add column if not exists description_ru text;
alter table public.financing_programs add column if not exists eligibility_notes_ru text;
alter table public.financing_programs add column if not exists insurance_type_ru text;
update public.banks set name_uz=coalesce(name_uz,name), name_ru=coalesce(name_ru,name) where name_uz is null or name_ru is null;
update public.dealers set name_uz=coalesce(name_uz,name),name_ru=coalesce(name_ru,name),region_uz=coalesce(region_uz,region),description_uz=coalesce(description_uz,description) where name_uz is null or name_ru is null or region_uz is null or description_uz is null;
update public.financing_programs set name_uz=coalesce(name_uz,name),name_ru=coalesce(name_ru,name) where name_uz is null or name_ru is null;
create or replace function public.require_ru_name_for_active_content() returns trigger language plpgsql as $$ begin if new.is_active and nullif(btrim(new.name_ru),'') is null then raise exception 'Russian name is required for active %', tg_table_name; end if; return new; end; $$;
drop trigger if exists banks_require_ru_name on public.banks;
create trigger banks_require_ru_name before insert or update on public.banks for each row execute procedure public.require_ru_name_for_active_content();
drop trigger if exists dealers_require_ru_name on public.dealers;
create trigger dealers_require_ru_name before insert or update on public.dealers for each row execute procedure public.require_ru_name_for_active_content();
drop trigger if exists financing_programs_require_ru_name on public.financing_programs;
create trigger financing_programs_require_ru_name before insert or update on public.financing_programs for each row execute procedure public.require_ru_name_for_active_content();
