import { AdminTable, Field } from "@/components/admin-ui";
import { createServiceRoleClient } from "@/supabase/server";
import { createBannerAction, toggleBannerAction } from "@/app/admin/marketplace-actions";

export default async function BannersPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const p = await searchParams;
  const result = await createServiceRoleClient().from("home_banners").select("*").order("sort_order").order("created_at", { ascending: false });
  return <div><h1 className="text-3xl font-black">Home bannerlar</h1>{p.error ? <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{p.error}</div> : null}<div className="mt-6 grid gap-6 xl:grid-cols-[1fr_420px]"><section>{result.data?.length ? <AdminTable><thead className="border-b bg-slate-50"><tr><th className="p-3">Banner</th><th className="p-3">Tartib</th><th className="p-3">Holat</th></tr></thead><tbody>{result.data.map((banner) => <tr key={banner.id} className="border-b last:border-0"><td className="p-3"><p className="font-bold">{banner.title_uz}</p><p className="text-xs text-slate-500">{banner.title_ru}</p><p className="mt-1 max-w-xl truncate text-xs text-slate-400">{banner.image_url}</p></td><td className="p-3">{banner.sort_order}</td><td className="p-3"><form action={toggleBannerAction}><input type="hidden" name="id" value={banner.id}/><input type="hidden" name="isActive" value={banner.is_active ? "" : "on"}/><button className="font-bold">{banner.is_active ? "Faol" : "Nofaol"}</button></form></td></tr>)}</tbody></AdminTable> : <p className="rounded-xl border border-dashed p-8 text-center text-slate-500">Bannerlar hali qo‘shilmagan.</p>}</section><form action={createBannerAction} className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="col-span-full text-xl font-black">Yangi banner</h2><Field name="titleUz" label="Sarlavha — UZ" required/><Field name="titleRu" label="Sarlavha — RU" required/><label className="text-sm font-semibold">Tavsif — UZ<textarea name="descriptionUz" className="mt-1 w-full rounded-lg border p-3"/></label><label className="text-sm font-semibold">Tavsif — RU<textarea name="descriptionRu" className="mt-1 w-full rounded-lg border p-3"/></label><Field name="imageUrl" label="Rasm URL" required/><Field name="ctaUz" label="Tugma — UZ"/><Field name="ctaRu" label="Tugma — RU"/><Field name="href" label="Havola"/><Field name="sortOrder" label="Tartib" type="number" defaultValue={0}/><label className="flex gap-2 text-sm font-semibold"><input type="checkbox" name="isActive" defaultChecked/>Faol</label><button className="col-span-full rounded-full bg-slate-950 py-3 font-bold text-white">Saqlash</button></form></div></div>;
}
